const fs=require('node:fs'),assert=require('node:assert/strict'),{JSDOM}=require('jsdom');
const Taste=require('../taste-model'),Art=require('../artwork-model'),Oracle=require('../oracle'),MediaArt=require('../netlify/functions/media-art');
assert(Taste.rewatchEvidence({rating:4.5}));assert(Taste.rewatchEvidence({owned:true}));assert(!Taste.rewatchEvidence({rating:3,watched:true}));assert(!Taste.eligibleDiscovery({overview:'An ordinary horror film'},{score:1,connection:{directors:[],writers:[],keywords:[],genres:['Horror']}}));assert(Taste.eligibleDiscovery({overview:'A surreal found footage film'},{}));
const newFilm={id:1,title:'New',meta:{genres:[],keywords:{keywords:[]}}},repeat={...newFilm,id:2,title:'Repeat',rating:4.5,oracleRewatch:true};const a=Oracle.rank(newFilm,{score:3,reasons:['A creator connection']},null,[],Date.now()),b=Oracle.rank(repeat,{score:3,reasons:['A creator connection']},null,[],Date.now());assert.equal(b.oracle.ledger.find(x=>x.title==='Prefer a new film').points,-4);assert.equal(b.oracle.ledger.find(x=>x.title==='Known affection').points,4);assert.equal(b.oracle.score,a.oracle.score,'A high rating alone does not beat an equally connected new film');
const at=Date.parse('2026-10-09T18:00:00Z');assert.equal(Art.choose([{id:1,title:'Resident Evil',release_date:'2002-01-01'},{id:2,title:'Resident Evil',release_date:'2026-09-01'}],{title:'Resident Evil',kind:'local'},at).id,2);assert.equal(Art.choose([{id:1,title:'Digger',release_date:'2026-01-01'},{id:2,title:'Digger',release_date:'2026-01-02'}],{title:'Digger',kind:'local'},at),null);assert.equal(Art.title('Guillermo del Toro’s Pan’s Labyrinth 20th Anniversary'),"Pan's Labyrinth");assert.equal(Art.sourcePoster({title:'Street Fighter'},[{title:'Street Fighter',poster:'https://cinemark.com/mandalorianposter.jpg'}]),null);assert(Art.sourcePoster({title:'Forgotten Island'},[{title:'Forgotten Island',poster:'https://cinemark.com/mdforgottenislandposter.jpg'}]));assert(!MediaArt.albumMatch({artistName:'Wrong Artist',collectionName:'Album'},'Right Artist','Album'));
(async()=>{for(const [route,file,section] of [['/','index.html','FILMS'],['/music/','music/index.html','MUSIC'],['/music/arena/','music/arena/index.html','MUSIC'],['/games/','games/index.html','GAMES']]){const d=new JSDOM(fs.readFileSync(__dirname+'/../'+file,'utf8'),{url:'https://example.test'+route,runScripts:'outside-only'});d.window.eval(fs.readFileSync(__dirname+'/../media-nav.js','utf8'));assert.equal(d.window.document.querySelector('.media-nav [aria-current]').textContent,section);assert.equal(d.window.document.querySelectorAll('.media-nav a').length,3);d.window.close();}
 const source=fs.readFileSync(__dirname+'/../music/arena/index.html','utf8');const d=new JSDOM(source,{url:'https://example.test/music/arena/',runScripts:'outside-only'}),w=d.window;
 w.fetch=async()=>({ok:true,json:async()=>({image:null,results:[],'release-groups':[]})});w.confirm=()=>true;w.alert=()=>{};w.localStorage.setItem('album_arena_state_v5',JSON.stringify({albums:[{id:'one',artist:'Artist',title:'Album',cover:'https://example.test/art.jpg',matches:2},{id:'two',artist:'Artist',title:'Album',cover:'',matches:9},{id:'other',artist:'Other',title:'Other album',cover:'https://example.test/other.jpg'}]}));
 w.eval([...w.document.querySelectorAll('script:not([src])')].map(s=>s.textContent).join('\n')+'\nwindow.arenaTest={read:()=>albums,cloud:applyCloudRecord,vote:()=>{applyWeightedMatch(albums[0],albums[1],-.8);renderEverything();buildNextMatchup();}};');
 assert.equal(w.arenaTest.read().length,2);assert.equal(w.arenaTest.read().find(a=>a.title==='Album').cover,'https://example.test/art.jpg');
 w.arenaTest.cloud({albums:[{id:'replacement',artist:'Artist',title:'Album',cover:'',matches:10},{id:'other',artist:'Other',title:'Other album',cover:''}]});assert.equal(w.arenaTest.read()[0].cover,'https://example.test/art.jpg');
 w.arenaTest.vote();assert.equal(JSON.parse(w.localStorage.getItem('album_arena_state_v5')).totalMatches,1);assert(w.document.querySelector('#cardLeft .album-cover').getAttribute('src'));d.window.close();
 const gameDom=new JSDOM(fs.readFileSync(__dirname+'/../games/index.html','utf8'),{url:'https://example.test/games/',runScripts:'outside-only'}),g=gameDom.window;
 g.fetch=async()=>({ok:true,json:async()=>({weather:{utc_offset_seconds:-21600,current:{cloud_cover:20,temperature_2m:68,is_day:1},daily:{sunset:['2026-10-09T18:59']}},image:null})});
 for(const script of g.document.querySelectorAll('script:not([src])'))g.eval(script.textContent);
 g.document.querySelector('#timeRow [data-val=quick]').click();g.document.querySelector('#weekRow [data-val=tight]').click();assert(!g.document.getElementById('goBtn').disabled);g.document.getElementById('goBtn').click();await new Promise(resolve=>setTimeout(resolve,10));assert(g.document.getElementById('gameName').textContent&&!/Shuffling/.test(g.document.getElementById('gameName').textContent));assert.match(g.document.getElementById('modeTag').textContent,/local pick/);gameDom.window.close();
 const savedFetch=global.fetch;global.fetch=async()=>({ok:true,json:async()=>({results:[{artistName:'Fixture Artist',collectionName:'Fixture Record',artworkUrl100:'https://example.test/100x100bb.jpg'}]})});try{const result=await MediaArt.handler({queryStringParameters:{kind:'album',artist:'Fixture Artist',title:'Fixture Record'}});assert.equal(JSON.parse(result.body).image,'https://example.test/600x600bb.jpg');}finally{global.fetch=savedFetch;}
 console.log('Combined media: navigation, exact artwork identity, rewatch preference, genre-only exclusion, Arena cover deduplication/cloud preservation and saved votes passed');
})().catch(e=>{console.error(e);process.exitCode=1});
