const assert=require('node:assert/strict'),C=require('../counter-model'),H=require('../hub-model');
const now=Date.now(),film={id:1,title:'Test'},hd={kind:'rent',provider:'Apple TV',price:5.99,format:'HD',link:'https://tv.apple.com/film'},snapshot={checkedAt:now,quoteCheckedAt:now,offers:[hd]};
const week=C.createAside(film,'week',now),forever=C.createAside(film,'forever',now,hd,6.99,'oracle');
assert.equal(C.asideActive(week,snapshot,now+7*86400000,'2026-10-14'),false);
assert.equal(C.setAside(film,snapshot,[forever],'roulette',now,'2026-10-07'),false);
assert.equal(C.setAside(film,snapshot,[forever],'oracle',now,'2026-10-07'),true);
assert.equal(C.asideActive({mode:'tonight',untilDate:'2026-10-08'},snapshot,now,'2026-10-08'),false);
const pause=C.createAside(film,'price',now,hd,6.99);
assert.equal(C.asideActive(pause,snapshot,now,'2026-10-07'),true);
assert.equal(C.asideActive(pause,{...snapshot,offers:[{...hd,price:3.99,format:'SD'}]},now,'2026-10-07'),true);
assert.equal(C.asideActive(pause,{...snapshot,stale:true,offers:[{...hd,price:3.99}]},now,'2026-10-07'),true);
assert.equal(C.asideActive(pause,{...snapshot,offers:[{...hd,price:3.99}]},now,'2026-10-07'),false);
assert.deepEqual(C.changes(null,snapshot,now),[]);
assert.deepEqual(C.changes(snapshot,{...snapshot,stale:true},now),[]);
assert.deepEqual(C.changes(snapshot,{...snapshot,offers:[{...hd,price:3.99,format:'SD'}]},now),[]);
const receipt=C.changes(snapshot,{...snapshot,offers:[{...hd,price:3.99}]},now)[0];assert.equal(receipt.from,5.99);assert.equal(receipt.to,3.99);assert.equal(receipt.url,hd.link);assert.equal(receipt.beforeCheckedAt,now);
const provider={kind:'subscription',provider:'Netflix',included:false};assert.deepEqual(C.changes({offers:[provider]},{offers:[{...provider,included:true}]},now),[],'Changing your services is not a provider arrival');
const hide={title:'Amélie',year:'2001',listingId:'original',createdAt:10},identity=H.theaterIdentity({id:'original',title:'Amélie'},{id:194,release_date:'2001-04-25'});
assert.equal(H.sameTheaterFilm(hide,identity),true,'Resolving artwork cannot undo a title hide');assert.equal(C.mergeHiddenFilms([hide],[],[]).length,1);
assert.equal(C.mergeHiddenFilms([hide],[],[{key:'title:amelie:2001',at:11}]).length,0);
assert.equal(C.mergeHiddenFilms([{...hide,createdAt:12}],[],[{key:'title:amelie:2001',at:11}]).length,1,'A later hide wins over a restore');
const seed={id:2,title:'Seed',rating:5,meta:{credits:{crew:[{job:'Director',name:'Test Person'}]}}},candidate={id:3,title:'Film',meta:seed.meta};assert.ok(H.affinity(candidate,[seed]).score>0);assert.equal(H.affinity(candidate,[seed],[{id:3,kind:'weak',seedId:2}]).score,0);assert.ok(H.affinity({...candidate,id:4},[seed],[{id:3,kind:'weak',seedId:2}]).score>0);
console.log('Counter: scoped/expiring deferrals, comparable fresh prices, receipts, late art identity, sync restore ordering and exact feedback passed');
