const assert=require('node:assert/strict');
const m=require('../rewind-model');
const p={link:'https://www.themoviedb.org/movie/1/watch?locale=US',flatrate:[{provider_name:'HBO Max',provider_id:1},{provider_name:'HBO Max Amazon Channel',provider_id:2}],rent:[{provider_name:'Amazon Video',provider_id:10}],buy:[{provider_name:'Apple TV Store',provider_id:2}],ads:[{provider_name:'Tubi',provider_id:73}]};
const offers=m.normalizeTMDB(p,['HBO Max','Prime Video']);
assert.equal(offers.find(o=>o.provider==='HBO Max').included,true);
assert.equal(offers.find(o=>o.provider==='HBO Max Amazon Channel').included,false);
assert.equal(offers.find(o=>o.provider==='Amazon Video').included,false);
assert.equal(offers.find(o=>o.provider==='Tubi').kind,'free');
assert.equal(m.summary(m.normalizeTMDB({buy:p.buy})).kind,'buy');
assert.match(m.summary(m.normalizeTMDB({buy:p.buy})).label,/no rental listed/);
assert.equal(m.summary(m.normalizeTMDB({})),null);
const quotes=m.normalizeWatchmode([{name:'Amazon Video',type:'rent',region:'US',price:19.99,format:'HD',web_url:'https://www.amazon.com/detail/1'},{name:'Amazon Video',type:'rent',region:'US',price:null,format:'4K'},{name:'Amazon Video',type:'rent',region:'GB',price:1,format:'HD'}]);
assert.equal(quotes.length,2);assert.equal(quotes[1].price,null);
assert.match(m.summary(quotes).label,/19\.99 \(HD\)/);
assert.equal(m.mergeOffers(m.normalizeTMDB({rent:p.rent}),quotes).length,2);
assert.equal(m.normalizeWatchmode([{name:'Store',type:'rent',region:'US',price:'3.99'}])[0].price,null);
assert.equal(m.safeLink('javascript:alert(1)'),null);
const window={start:'2026-08-01',end:'2026-08-31',today:'2026-10-04'};
const movie={id:1,title:'Feature',poster_path:'/poster.jpg',genre_ids:[18]};
const details={runtime:100,credits:{crew:[{job:'Director',name:'Jane'}]},release_dates:{results:[{iso_3166_1:'US',release_dates:[{type:3,release_date:'2026-08-28T00:00:00Z'}]}]}};
assert.equal(m.discoveryMovie(movie,details,window).usReleaseDate,'2026-08-28');
assert.equal(m.discoveryMovie(movie,{...details,runtime:10},window),null);
assert.equal(m.discoveryMovie(movie,{...details,release_dates:{results:[{iso_3166_1:'GB',release_dates:[{type:3,release_date:'2026-08-28T00:00:00Z'}]}]}},window),null);
assert.equal(m.discoveryMovie(movie,{...details,release_dates:{results:[{iso_3166_1:'US',release_dates:[{type:1,release_date:'2026-08-28T00:00:00Z'}]}]}},window),null);
const rerelease={...details,release_dates:{results:[{iso_3166_1:'US',release_dates:[{type:3,release_date:'1991-07-03T00:00:00Z'},{type:3,release_date:'2026-08-28T00:00:00Z'}]}]}};
assert.equal(m.discoveryMovie(movie,rerelease,window),null);assert.ok(m.discoveryMovie(movie,rerelease,window,true));
console.log('Rewind: US feature verification, rereleases, channels, free/rent/buy separation, null quotes, price formats passed');
const r=require('../release-model');
const early={id:90,release_dates:{results:[{iso_3166_1:'US',release_dates:[{type:3,release_date:'2026-09-10'}]}]}};
const comparable=n=>({id:n,release_dates:{results:[{iso_3166_1:'US',release_dates:[{type:3,release_date:'2026-05-01'},{type:4,release_date:r.addDays('2026-05-01',n+30)}]}]}});
assert.equal(r.digitalEstimate(early,[1,2,3,4].map(comparable),'2026-10-05'),null);
const estimate=r.digitalEstimate(early,[1,2,3,4,5,5].map(comparable),'2026-10-05');assert.equal(estimate.samples,5);assert.equal(estimate.start,'2026-10-11');assert.equal(estimate.end,'2026-10-14');
assert.equal(r.digitalEstimate(comparable(1),[1,2,3,4,5,6].map(comparable),'2026-10-05'),null);
assert.equal(r.group({offers:[{kind:'subscription',included:true}]}),'now');assert.equal(r.group({offers:[{kind:'subscription',included:false}]}),'waiting');assert.equal(r.group({offers:[{kind:'buy'}]}),'paid');assert.equal(r.group({stale:true,offers:[{kind:'free'}]}),'waiting');
const paid={kind:'rent',provider:'Apple TV',format:'HD',price:19.99};const freeNull={...paid,price:null};
let history=r.recordQuotes([], [paid,freeNull],Date.parse('2026-09-01'));assert.equal(history.length,1);history=r.recordQuotes(history,[paid],Date.parse('2026-09-01'));assert.equal(history.length,1);history=r.recordQuotes(history,[{...paid,price:5.99}],Date.parse('2026-09-08'));assert.equal(r.latestPriceChange(history,[{...paid,price:5.99}]).from,19.99);
assert.equal(r.latestPriceChange(history,[{...paid,format:'4K',price:5.99}]),null);
const current={id:99,priceHistory:r.recordQuotes([],[paid],Date.parse('2026-09-25'))};const drops=[1,2,3,4,5].map(id=>({id,priceHistory:r.recordQuotes(r.recordQuotes([],[paid],Date.parse('2026-08-01')),[{...paid,price:5.99}],Date.parse('2026-08-08'))}));
assert.ok(r.priceEstimate(current,[paid],drops,'2026-09-28',5.99));assert.equal(r.priceEstimate(current,[paid],drops.slice(0,4),'2026-09-28',5.99),null);
assert.equal(r.priceEstimate(current,[{...paid,format:'4K'}],drops,'2026-09-28',5.99),null);
const feed={today:'2026-10-05',announcements:[{tmdbId:1,kind:'subscription',region:'GB',sourceUrl:'https://test.com',date:'2026-10-10'},{tmdbId:1,kind:'subscription',region:'US',sourceUrl:'javascript:bad',date:'2026-10-10'},{tmdbId:1,kind:'subscription',region:'US',sourceUrl:'https://test.com',date:'2026-10-10'}]};assert.equal(r.matchingAnnouncements(feed,1).length,1);
assert.deepEqual(r.preference({mode:'bad',maxPrice:-1}),{mode:'any',maxPrice:7.99});
console.log('Release timelines: estimate minimums, US records, offer groups, quote history, comparable-format price windows, announcement matching passed');
const costs=[{kind:'rent',provider:'Apple TV Store',price:19.99,format:'HD'},{kind:'rent',provider:'Amazon',price:19.98,format:'SD'},{kind:'rent',provider:'Amazon',price:19.99,format:'4K'},{kind:'rent',provider:'Fandango at Home',price:14.99,format:'HD'}];
const cost=r.cost(costs,7.99);assert.equal(cost.price,19.99);assert.equal(cost.offer.format,'4K');assert.equal(cost.band,'premium');assert.equal(cost.cheaper.price,14.99);assert.match(cost.caption,/Apple TV/);assert.match(cost.caption,/Prime Video/);
assert.equal(r.cost([{kind:'subscription',included:true,provider:'Shudder'},...costs]).badge,'INCLUDED');assert.equal(r.cost([{kind:'free',provider:'Tubi',adSupported:true}]).badge,'FREE');
assert.equal(r.cost([{kind:'rent',provider:'Apple TV',price:7.99,format:'HD'}],7.99).band,'cheap');assert.equal(r.cost([{kind:'buy',provider:'Apple TV',price:7.99,format:'HD'}],7.99).band,'buy');assert.equal(r.cost([{kind:'rent',provider:'Apple TV',price:null}]).price,null);assert.equal(r.cost(costs,7.99,true).band,'waiting');
const rows=r.compactOffers([{...costs[0],format:'SD'},costs[0],{...costs[0],format:'4K'}]);assert.equal(rows.length,1);assert.match(rows[0].format,/4K/);assert.match(rows[0].format,/HD/);
console.log('Cost cards: Apple/Prime priority, HD/4K comparisons, cheaper alternatives, included vs free, purchase separation, unknown prices, compact format rows passed');
