const assert=require('node:assert/strict');
const m=require('../rewind-model');
const p={link:'https://www.themoviedb.org/movie/1/watch?locale=US',flatrate:[{provider_name:'HBO Max',provider_id:1},{provider_name:'HBO Max Amazon Channel',provider_id:2}],rent:[{provider_name:'Amazon Video',provider_id:10}],buy:[{provider_name:'Apple TV Store',provider_id:2}],ads:[{provider_name:'Tubi',provider_id:73}]};
const offers=m.normalizeTMDB(p,['HBO Max','Prime Video']);
assert.equal(offers.find(o=>o.provider==='HBO Max').included,true);
assert.equal(offers.find(o=>o.provider==='HBO Max Amazon Channel').included,false);
assert.equal(offers.find(o=>o.provider==='Amazon Video').included,false);
assert.equal(offers.find(o=>o.provider==='Tubi').kind,'free');
assert.equal(m.summary(m.normalizeTMDB({buy:p.buy})).kind,'buy');
assert.match(m.summary(m.normalizeTMDB({buy:p.buy})).label,/no rental listed/);
assert.equal(m.summary(m.normalizeTMDB({})),null);
const quotes=m.normalizeWatchmode([{name:'Amazon Video',type:'rent',region:'US',price:19.99,format:'HD',web_url:'https://www.amazon.com/detail/1'},{name:'Amazon Video',type:'rent',region:'US',price:null,format:'4K'},{name:'Amazon Video',type:'rent',region:'GB',price:1,format:'HD'}]);
assert.equal(quotes.length,2);assert.equal(quotes[1].price,null);
assert.match(m.summary(quotes).label,/19\.99 \(HD\)/);
assert.equal(m.mergeOffers(m.normalizeTMDB({rent:p.rent}),quotes).length,2);
assert.equal(m.normalizeWatchmode([{name:'Store',type:'rent',region:'US',price:'3.99'}])[0].price,null);
assert.equal(m.safeLink('javascript:alert(1)'),null);
const window={start:'2026-08-01',end:'2026-08-31',today:'2026-10-04'};
const movie={id:1,title:'Feature',poster_path:'/poster.jpg',genre_ids:[18]};
const details={runtime:100,credits:{crew:[{job:'Director',name:'Jane'}]},release_dates:{results:[{iso_3166_1:'US',release_dates:[{type:3,release_date:'2026-08-28T00:00:00Z'}]}]}};
assert.equal(m.discoveryMovie(movie,details,window).usReleaseDate,'2026-08-28');
assert.equal(m.discoveryMovie(movie,{...details,runtime:10},window),null);
assert.equal(m.discoveryMovie(movie,{...details,release_dates:{results:[{iso_3166_1:'GB',release_dates:[{type:3,release_date:'2026-08-28T00:00:00Z'}]}]}},window),null);
assert.equal(m.discoveryMovie(movie,{...details,release_dates:{results:[{iso_3166_1:'US',release_dates:[{type:1,release_date:'2026-08-28T00:00:00Z'}]}]}},window),null);
const rerelease={...details,release_dates:{results:[{iso_3166_1:'US',release_dates:[{type:3,release_date:'1991-07-03T00:00:00Z'},{type:3,release_date:'2026-08-28T00:00:00Z'}]}]}};
assert.equal(m.discoveryMovie(movie,rerelease,window),null);assert.ok(m.discoveryMovie(movie,rerelease,window,true));
console.log('Rewind: US feature verification, rereleases, channels, free/rent/buy separation, null quotes, price formats passed');
