const assert=require('node:assert/strict'),O=require('../oracle');const at=Date.UTC(2026,9,5,20),m={id:1,title:'Mountain Moon',runtime:95,genres:[{name:'Horror'}],keywords:{keywords:[{name:'isolation'},{name:'moon'}]}},fit={score:3,reasons:['Same director as a favorite']};const context={checkedAt:at,weather:{current:{temperature_2m:35,cloud_cover:90,relative_humidity_2m:90,is_day:0},daily:{daylight_duration:[35000]}},news:[]};const r=O.rank(m,fit,context,[],at,true);assert.ok(r.oracle.score>=3&&r.oracle.score<=3.8);assert.ok(r.oracle.nudge.length);assert.ok(r.oracle.ledger.length>=25);const missing=O.rank(m,{score:0,reasons:[]},null,[],at);assert.equal(missing.oracle.ledger.find(x=>x.title==='Humidity').value,'Unavailable');assert.match(missing.oracle.verdict,/No strong personal/);assert.ok(O.moon(at).illumination>=0&&O.moon(at).illumination<=100);console.log('Oracle: bounded atmospheric ranking, explicit missing data, evidence report and approximate moon passed');

const H=require('../hub-model'),crimeSeed={id:100,title:'The Departed',rating:5,meta:{keywords:{keywords:[{name:'police'},{name:'undercover'}]},genres:[{name:'Crime'}]}},crimeFilm={id:101,title:'A Crime Film',meta:{keywords:{keywords:[{name:'police'},{name:'undercover'}]},genres:[{name:'Crime'}]}};
const crimeFit=H.affinity(crimeFilm,[crimeSeed]),crimeReading=O.reading(crimeFilm,crimeFit,at);
assert.match(crimeReading.text,/The Departed 5\/5/);assert.doesNotMatch(crimeReading.text,/Shares police|You own|watched.*more than once/);
assert.notEqual(crimeReading.heading,O.reading(m,fit,at).heading,'Film metadata changes the reading');
assert.equal(O.reading(crimeFilm,crimeFit,at).text,crimeReading.text,'Copy is stable when reopening a reading');
assert.doesNotMatch(O.reading({id:999,title:'Unknown'},null,at).text,/rated|own|favorite/,'Missing evidence invents no personal history');
console.log('Oracle readings: film-specific themes, grounded ratings, stable copy and no invented personal signals passed');
