const assert=require('node:assert/strict'),O=require('../oracle');const at=Date.UTC(2026,9,5,20),m={id:1,title:'Mountain Moon',runtime:95,genres:[{name:'Horror'}],keywords:{keywords:[{name:'isolation'},{name:'moon'}]}},fit={score:3,reasons:['Same director as a favorite']};const context={checkedAt:at,weather:{current:{temperature_2m:35,cloud_cover:90,relative_humidity_2m:90,is_day:0},daily:{daylight_duration:[35000]}},news:[]};const r=O.rank(m,fit,context,[],at,true);assert.ok(r.oracle.score>=3&&r.oracle.score<=3.8);assert.ok(r.oracle.nudge.length);assert.ok(r.oracle.ledger.length>=25);const missing=O.rank(m,{score:0,reasons:[]},null,[],at);assert.equal(missing.oracle.ledger.find(x=>x.title==='Humidity').value,'Unavailable');assert.match(missing.oracle.verdict,/No strong personal/);assert.ok(O.moon(at).illumination>=0&&O.moon(at).illumination<=100);console.log('Oracle: bounded atmospheric ranking, explicit missing data, evidence report and approximate moon passed');

const H=require('../hub-model'),crimeSeed={id:100,title:'The Departed',rating:5,meta:{keywords:{keywords:[{name:'police'},{name:'undercover'}]},genres:[{name:'Crime'}]}},crimeFilm={id:101,title:'A Crime Film',meta:{keywords:{keywords:[{name:'police'},{name:'undercover'}]},genres:[{name:'Crime'}]}};
const crimeFit=H.affinity(crimeFilm,[crimeSeed]),crimeReading=O.reading(crimeFilm,crimeFit,at);
assert.match(crimeReading.text,/The Departed 5\/5/);assert.doesNotMatch(crimeReading.text,/Shares police|You own|watched.*more than once/);
assert.notEqual(crimeReading.heading,O.reading(m,fit,at).heading,'Film metadata changes the reading');
assert.equal(O.reading(crimeFilm,crimeFit,at).text,crimeReading.text,'Copy is stable when reopening a reading');
assert.doesNotMatch(O.reading({id:999,title:'Unknown'},null,at).text,/rated|own|favorite/,'Missing evidence invents no personal history');
console.log('Oracle readings: film-specific themes, grounded ratings, stable copy and no invented personal signals passed');

// The displayed contribution ledger must reconcile exactly with the score.
const detailedSeed={id:701,title:'Known favorite',rating:5,owned:true,favorite:true,rewatches:3,meta:{genres:[{name:'Horror'}],keywords:{keywords:[{name:'mountain'}]},credits:{crew:[{job:'Director',name:'Director Name'},{job:'Writer',name:'Writer Name'}]}}};
const detailed={id:702,title:'Mountain Moon',release_date:'1985-01-01',meta:{runtime:95,genres:[{name:'Horror'}],keywords:{keywords:['mountain','winter','swamp','rain','storm','night','werewolf'].map(name=>({name}))},credits:detailedSeed.meta.credits}};
const rich={checkedAt:at,weather:{current:{temperature_2m:35,apparent_temperature:30,relative_humidity_2m:90,cloud_cover:90,precipitation:.1,wind_speed_10m:15,wind_gusts_10m:30,pressure_msl:990,surface_pressure:890},daily:{daylight_duration:[30000],sunset:['2026-10-05T12:00'],precipitation_probability_max:[80]}},news:[{title:'Director Name discusses a movie',publishedAt:new Date(at-86400000).toISOString()}]};
const diary=[{title:'An eighties favorite',rating:5,release_date:'1987-01-01',watchedAt:'2026-10-01'},detailedSeed];
const detailedFit=H.affinity(detailed,[detailedSeed]),scored=O.rank(detailed,detailedFit,rich,diary,at,true).oracle;
assert.ok(Math.abs(scored.ledger.reduce((s,x)=>s+x.points,0)-scored.score)<1e-9,'Ledger contributions add to the final score without double counting');
for(const title of ['Temperature','Feels like','Humidity','Cloud cover','Rain / snow','Wind','Gusts','Air pressure','Surface pressure','Daylight','Sunset','Rain probability','Moon','Season','Release year','Director','Writers','Genres','Keywords','Local screening','Recent film news','Ownership / favorites','Repeat watches','High ratings'])assert.ok(scored.ledger.find(x=>x.title===title).points>0,title+' has a reachable scoring rule');
assert.ok(scored.contextScale<1,'Overflow scales all context contributions proportionately');
const zero=O.rank({id:800,title:'Unspecified'},null,null,[],at).oracle;
for(const title of ['Temperature','Feels like','Humidity','Wind','Gusts','Air pressure','Surface pressure','Daylight','Sunset','Rain probability','Release year','Recent film news'])assert.equal(zero.ledger.find(x=>x.title===title).points,0,title+' does not invent missing evidence');
const late=O.rank(detailed,detailedFit,null,[],Date.UTC(2026,9,6,4)).oracle;assert.ok(late.ledger.find(x=>x.title==='Runtime').points>0,'Late weekday runtime rule actually weighs');
const badNews={news:[{title:'Director Namesake speaks',publishedAt:new Date(at-86400000).toISOString()},{title:'Director Name speaks',publishedAt:new Date(at-20*86400000).toISOString()}]};assert.equal(O.rank(detailed,detailedFit,badNews,[],at).oracle.related,undefined,'Stale headlines and partial names do not match');
assert.equal(O.rank(detailed,detailedFit,rich,[{...diary[0],watchedAt:'2027-01-01'}],at).oracle.ledger.find(x=>x.title==='Release year').points,0,'Future diary dates do not influence an era');
console.log('Oracle ledger: every scoring rule reachable, exact score accounting, cap scaling, missing/future data and fresh exact news matches passed');

const contender=(id,title,taste,context,ledger)=>({id,title,fit:{reasons:['Same director as a favorite']},oracle:{score:taste+context,tasteScore:taste,atmosphereScore:context,ledger}});
const winner=contender(901,'Winner',3,.2,[{title:'Director',points:3,group:'taste'},{title:'Temperature',points:.2,group:'atmosphere'},{title:'Inferred atmosphere',points:0,group:'summary'}]);
const runner=contender(902,'Runner',3.1,0,[{title:'Director',points:3.1,group:'taste'}]);
const comparison=O.compare([runner,winner]);assert.equal(comparison.winner.title,'Winner');assert.equal(comparison.count,2);assert.equal(comparison.alternatives[0].weatherTipped,true);assert.ok(Math.abs(comparison.alternatives[0].deltas.reduce((s,x)=>s+x.points,0)-comparison.alternatives[0].gap)<1e-9,'All differences reconcile with the score gap');assert.equal(comparison.alternatives[0].gains[0].title,'Temperature');assert.equal(comparison.alternatives[0].losses[0].title,'Director');
const tied=O.compare([winner,{...winner,id:903,title:'Equal'}]);assert.equal(tied.alternatives[0].tie,true);assert.equal(tied.alternatives[0].weatherTipped,false);assert.equal(tied.alternatives[0].close,false);
const close=O.compare([winner,contender(904,'Near',3.15,0,[{title:'Director',points:3.15,group:'taste'}])]);assert.equal(close.alternatives[0].close,true);
assert.equal(O.compare([winner]).alternatives.length,0,'Single candidate does not invent competition');assert.equal(O.compare([]),null);assert.equal(O.compare([winner,runner,...[1,2,3].map(id=>contender(id,'Other '+id,1,0,[]))]).alternatives.length,3,'Only strongest three runners-up shown');
const localWinner=contender(905,'Local',3,.15,[{title:'Director',points:3,group:'taste'},{title:'Local screening',points:.15,group:'atmosphere'}]);assert.equal(O.compare([localWinner,runner]).alternatives[0].weatherTipped,false,'Local screening is not misattributed to weather');
console.log('Oracle comparisons: exact gaps and deltas, strongest alternatives, close calls, ties, weather counterfactual and single candidate passed');

const sunsetAt=Date.UTC(2026,9,6,23,30),sunFilm={id:9991,title:'Evening Example',meta:{runtime:95,genres:[{name:'Drama'}],keywords:{keywords:[{name:'grief'}]}}},sunContext={weather:{daily:{sunset:['2026-10-06T19:05']}}};
const sunResult=O.rank(sunFilm,{score:0,reasons:[]},sunContext,[],sunsetAt).oracle,sunTile=sunResult.ledger.find(x=>x.title==='Sunset');assert.match(sunTile.story,/1 hour 35 minutes/);assert.match(sunTile.story,/within ten minutes of sunset/);assert.ok(sunTile.points>0,'Exact runtime-to-sunset alignment weighs');
const wrongDate=O.rank(sunFilm,null,{weather:{daily:{sunset:['2026-10-05T19:05']}}},[],sunsetAt).oracle.ledger.find(x=>x.title==='Sunset');assert.equal(wrongDate.points,0);assert.equal(wrongDate.value,'Unavailable','Yesterday’s sunset is never narrated as today’s');
const noRuntime=O.rank({...sunFilm,meta:{genres:[]}},null,sunContext,[],sunsetAt).oracle.ledger.find(x=>x.title==='Sunset');assert.match(noRuntime.story,/runtime is missing/);assert.equal(noRuntime.points,0);
const lateSun=O.rank(sunFilm,null,sunContext,[],Date.UTC(2026,9,7,2)).oracle.ledger.find(x=>x.title==='Sunset');assert.match(lateSun.story,/Sunset was 55 minutes ago/);assert.doesNotMatch(lateSun.story,/ends as the light changes/);
const lowPressure=O.rank({...sunFilm,meta:{genres:[{name:'Thriller'}]}},null,{weather:{current:{pressure_msl:995}}},[],sunsetAt).oracle.ledger.find(x=>x.title==='Air pressure');assert.match(lowPressure.story,/rising air/);assert.match(lowPressure.story,/Evening Example/);assert.equal(lowPressure.source.url,'https://www.weather.gov/jkl/education');
const lunarAt=Date.UTC(2000,0,6,18,14)+26*86400000,moonTile=O.rank(sunFilm,null,null,[],lunarAt).oracle.ledger.find(x=>x.title==='Moon');assert.match(moonTile.value,/Waning crescent/);assert.match(moonTile.story,/Christopher Penczak/);assert.match(moonTile.story,/grief/);assert.ok(moonTile.points>0,'Sourced waning symbolism can affect a grief film');
assert.ok(sunResult.ledger.every(x=>typeof x.story==='string'&&x.story.length>0),'Every factor has an interpretation alongside its formula');
assert.equal(O.rank({id:987,title:'Research',meta:{genres:[]}},null,{weather:{current:{precipitation:.1}}},[],sunsetAt).oracle.ledger.find(x=>x.title==='Rain / snow').points,0,'Sea substring in research does not forge a water motif');
console.log('Oracle interpretations: minute-accurate sunset alignment, past/missing runtime and stale-date exclusions, sourced pressure/moon narratives and every-factor copy passed');
