(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.GameHistory=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
 const apps=new Set(['hbomax','youtubetv','spotify','disney','hulu','appletv','primevideo','netflix','peacock','youtube']);
 function key(s){const n=String(s||'').replace(/[™®]/g,'').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/playstation[^a-z]*5/g,'').replace(/[^a-z0-9]/g,'');const aliases={thestanleyparableultradeluxe:'stanleyparableultradeluxe',thewitcher3wildhuntremastered:'witcher3wildhunt',thewitcher3wildhunt:'witcher3wildhunt',tonyhawksproskater12:'tonyhawksproskater12','12minutes':'twelveminutes',residentevil7biohazard:'residentevil7',ittakestwops4ps5:'ittakestwo',grandtheftautovplaystation5:'grandtheftautov',returnal:'returnal'};return aliases[n]||n;}
 function merge(pool,records){const groups=new Map();for(const r of records||[]){const k=key(r.name);if(apps.has(k))continue;if(!groups.has(k))groups.set(k,[]);groups.get(k).push(r);}const result=new Map();for(const g of pool){const k=key(g.name);if(!result.has(k))result.set(k,{...g});}for(const [k,rows] of groups){const existing=result.get(k);const perPlatform=new Map();for(const r of rows){const p=r.platform||'unknown',old=perPlatform.get(p);if(!old||Number(r.minutes)>Number(old.minutes))perPlatform.set(p,r);}const unique=[...perPlatform.values()],minutes=unique.reduce((sum,r)=>sum+(r.minutes||0),0),lastPlayed=rows.map(r=>r.lastPlayed).filter(Boolean).sort().at(-1),firstPlayed=rows.map(r=>r.firstPlayed).filter(Boolean).sort()[0],cover=[...rows].sort((a,b)=>String(b.lastPlayed).localeCompare(String(a.lastPlayed))).find(r=>r.cover)?.cover;
  const g=existing||{name:rows[0].name,genre:'From your PlayStation library',type:'Unclassified',hours:null,replay:null,note:'',energy:'med',weather:'neutral',bucket:'Active'};
  g.history={minutes,approximate:rows.some(r=>/^about|\(|less than/.test(r.playtimeText||'')),lastPlayed,firstPlayed,platforms:[...perPlatform.keys()],entries:rows.length,duplicateEntries:rows.length-unique.length,cover};
  if(['Never Started','Barely Started'].includes(g.bucket)&&minutes>0)g.bucket=minutes<120?'Barely Started':'Active';
  if(!existing)g.bucket=minutes<120?'Barely Started':'Active';
  result.set(k,g);
 }return [...result.values()];}
 function evidence(g,pool){const own=g.history;let score=0,connection=null;for(const seed of pool){if(seed===g||!seed.history||seed.history.minutes<600||!seed.genre||seed.type==='Unclassified')continue;const a=new Set((g.genre+' '+g.type).toLowerCase().split(/[^a-z]+/).filter(w=>w.length>3&&!['game','from','your','playstation','library','story','unclassified'].includes(w)));const matches=(seed.genre+' '+seed.type).toLowerCase().split(/[^a-z]+/).filter(w=>a.has(w));const weight=Math.min(2,new Set(matches).size*.5+Math.min(1,seed.history.minutes/6000));if(matches.length&&weight>score){score=weight;connection=seed;}}
  const logged=own?.minutes>=600?1:0;return {score:score+logged,connection,logged};}
 return {key,merge,evidence};
});
