function appendNote(root,text,cls='offer-note'){const p=document.createElement('p');p.className=cls;p.textContent=text;root.appendChild(p);return p;}
function releaseSource(root,label,url){const safe=RewindModel.safeLink(url);if(!safe)return;const a=document.createElement('a');a.href=safe;a.target='_blank';a.rel='noopener noreferrer';a.textContent=label;root.appendChild(a);}
function renderAvailability(movie,status,context={}) {
  const wrap=document.createElement('div');wrap.className='availability';
  if(status.stale)appendNote(wrap,'Could not refresh. Previous availability may have changed.','lookup-warning');
  if(status.previousLabel&&status.previousLabel!==status.label)appendNote(wrap,'Previously: '+status.previousLabel);
  const all=ReleaseModel.compactOffers(status.offers),cost=ReleaseModel.cost(status.offers,rentalBudget,status.stale);
  const chosen=all.filter(o=>o.kind==='physical'||o.kind==='free'||o.kind==='subscription'&&o.included||o.kind==='rent'&&['apple','amazon'].includes(ReleaseModel.storeKey(o.provider)));
  if(!chosen.length&&cost.offer)chosen.push(cost.offer);
  const rows=(root,offers)=>{for(const o of offers){const row=document.createElement('div');row.className='offer-row';const name=document.createElement(o.link?'a':'span');name.textContent=o.provider;if(o.link){name.href=o.link;name.target='_blank';name.rel='noopener noreferrer';}const price=document.createElement('strong');price.textContent=o.kind==='physical'?(o.format||'Physical copy')+' · owned':o.kind==='subscription'?(o.included?'Included':'Subscription'):o.kind==='free'?'Free'+(o.adSupported?' with ads':''):typeof o.price==='number'?(o.kind==='buy'?'Buy ':'Rent ')+'$'+o.price.toFixed(2)+(o.format?' · '+o.format:''):'Price not supplied';row.append(name,price);root.appendChild(row);}};
  const heading=document.createElement('h4');heading.textContent='Where to watch';wrap.appendChild(heading);rows(wrap,chosen.slice(0,3));
  if(!all.length)appendNote(wrap,'No confirmed viewing option yet.');
  const remaining=all.filter(o=>!chosen.slice(0,3).includes(o));
  if(remaining.length){const more=document.createElement('details');more.className='source-disclosure viewing-options';const summary=document.createElement('summary');summary.textContent='More viewing options · '+remaining.length;more.appendChild(summary);rows(more,remaining);wrap.appendChild(more);}
  if(status.checkedAt)appendNote(wrap,(status.stale?'Previous check · ':'Checked · ')+new Date(status.checkedAt).toLocaleString('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}),'checked-note');
  const sources=document.createElement('details');sources.className='source-disclosure release-sources';const summary=document.createElement('summary');summary.textContent='Release dates & sources';sources.append(summary,renderReleaseTimeline(movie,status,context),renderReleaseEvidence(movie,status,context));
  if(status.priceWarning)appendNote(sources,status.priceWarning,'lookup-warning');appendNote(sources,'US listings: JustWatch. '+(status.priceSources?.length?'Price sources: '+status.priceSources.join(' / ')+'.':'No current dollar quote supplied.'));if(status.quoteCheckedAt)appendNote(sources,'Prices checked '+new Date(status.quoteCheckedAt).toLocaleString('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})+'. Store checkout is final.');wrap.appendChild(sources);
  return wrap;
}
function renderReleaseEvidence(movie,status,context={}){
  const root=document.createElement('section');root.className='release-timeline';const heading=document.createElement('h4');heading.textContent='Release timeline';root.appendChild(heading);
  const today=discoveryWindow().today;const details=status.details||movie.detailsSnapshot;const stage=ReleaseModel.stages(details,today);
  const row=(label,text,certainty,sourceLabel,sourceUrl)=>{const item=document.createElement('div');item.className='timeline-item';const name=document.createElement('strong');name.textContent=label;item.appendChild(name);const badge=document.createElement('span');badge.className='certainty '+certainty.toLowerCase();badge.textContent=certainty;item.appendChild(badge);appendNote(item,text,'timeline-text');if(sourceUrl)releaseSource(item,sourceLabel,sourceUrl);root.appendChild(item);return item;};
  const tmdbUrl=`https://www.themoviedb.org/movie/${movie.id}/releases`;
  if(stage.limited)row('Limited theatrical',formatFilmDate(stage.limited),'Listed','TMDB US dates',tmdbUrl);
  if(stage.wide){const elapsed=ReleaseModel.days(stage.wide,today);row('Wide theatrical',formatFilmDate(stage.wide)+(elapsed>=0?` · ${elapsed} days since US release`:''),'Listed','TMDB US dates',tmdbUrl);}
  if(!stage.limited&&!stage.wide)row('Theatrical window','No US theatrical date listed.','Unknown');
  else appendNote(root,'The end of the theater run is not published here. Digital availability can overlap with screenings.');
  const announcements=status.announcements||[];
  const digitalAnnouncement=announcements.find(a=>a.kind==='digital');const digital=digitalAnnouncement?.date||stage.digital;
  if(digital){const anchor=stage.wide||stage.limited;const gap=anchor?ReleaseModel.days(anchor,digital):null;row('Digital rent / buy',formatFilmDate(digital)+(gap!==null&&gap>=0?` · ${gap} days after theatrical release`:'')+'. A digital date does not confirm a rental price or subscription. ',digitalAnnouncement?'Announced':'Listed',digitalAnnouncement?.source||'TMDB US dates',digitalAnnouncement?.sourceUrl||tmdbUrl);}
  else if((status.offers||[]).some(o=>['rent','buy'].includes(o.kind)))row('Digital rent / buy','Available in the offers above. First release date not supplied.','Observed');
  else {const estimate=ReleaseModel.digitalEstimate(details||{},context.details||[],today);if(estimate)row('Expected digital window',formatFilmDate(estimate.start)+' to '+formatFilmDate(estimate.end)+`. Based on ${estimate.samples} recently browsed films with listed US theatrical and digital dates (middle 60% of observed gaps). Broad comparison, not a studio promise.`+(estimate.overdue?' This window has passed without a verified listing.':''),'Estimate');else row('Digital rent / buy','Date not announced. Not enough comparable US releases to estimate a window.','Unknown');}
  const included=(status.offers||[]).filter(o=>o.kind==='subscription'&&o.included);
  if(included.length)row('Subscription streaming','Currently listed on '+[...new Set(included.map(o=>o.provider))].join(', ')+'.','Observed');
  const subscriptions=announcements.filter(a=>a.kind==='subscription');
  for(const a of subscriptions){const n=a.date?ReleaseModel.days(today,a.date):null;const text=a.date?`${a.provider} · ${formatFilmDate(a.date)}`+(n>0?` · in ${n} day${n===1?'':'s'}`:!(status.offers||[]).some(o=>o.kind==='subscription'&&RewindModel.serviceKey(o.provider)===RewindModel.serviceKey(a.provider))?' · announced date reached; current availability not verified':''):`${a.provider} announced; date to be confirmed`;row('Subscription announcement',text,'Announced',a.source,a.sourceUrl);appendNote(root,'Announcement checked '+formatFilmDate(a.checkedAt)+'.');}
  const seen=new Set(subscriptions.map(a=>`${RewindModel.serviceKey(a.provider)}:${a.date}`));
  for(const c of status.calendar||[]){if(c.region&&c.region!=='US')continue;if(!c.source_name||!ReleaseModel.date(c.source_release_date)||!RewindModel.SERVICE_CHOICES.some(name=>RewindModel.serviceKey(name)===RewindModel.serviceKey(c.source_name)))continue;const key=RewindModel.serviceKey(c.source_name)+':'+c.source_release_date;if(seen.has(key))continue;seen.add(key);row('Upcoming service listing',c.source_name+' · '+formatFilmDate(c.source_release_date)+'. Calendar listing; check current US offers when the date arrives.','Listed','Watchmode release calendar','https://api.watchmode.com/docs');}
  if(!included.length&&!subscriptions.length&&!seen.size)row('Subscription streaming','No service-specific release date announced in the connected sources.','Unknown');
  for(const a of announcements.filter(a=>a.kind==='theatrical'))row('Theatrical announcement',a.date?formatFilmDate(a.date):'Date to be confirmed','Announced',a.source,a.sourceUrl);
  const quotes=(status.offers||[]).filter(o=>o.kind==='rent'&&typeof o.price==='number').sort((a,b)=>a.price-b.price);
  if(quotes.length){const cheapest=quotes[0];row('Current rental quote',`$${cheapest.price.toFixed(2)} on ${cheapest.provider}${cheapest.format?' · '+cheapest.format:''}`+(status.stale?' · previous check':''),'Observed');}
  const change=ReleaseModel.latestPriceChange(movie.priceHistory,status.offers);if(change)row('Observed rental price drop',`$${change.from.toFixed(2)} → $${change.to.toFixed(2)} on ${change.provider}${change.format?' · '+change.format:''}. Observed ${new Date(change.at).toLocaleDateString('en-US',{month:'short',day:'numeric'})}.`,'Observed');
  const priceAnnouncements=announcements.filter(a=>a.kind==='price'&&typeof a.price==='number');
  for(const a of priceAnnouncements)row('Announced price change',`$${a.price.toFixed(2)} on ${a.provider}${a.date?' from '+formatFilmDate(a.date):' · date to be confirmed'}`,'Announced',a.source,a.sourceUrl);
  if(!priceAnnouncements.length){const pref=ReleaseModel.preference(movie.alert);const forecast=ReleaseModel.priceEstimate(movie,status.offers,context.movies||[],today,pref.mode==='rental'?pref.maxPrice:9.99);if(forecast)row('Expected cheaper rental',`At or below $${forecast.threshold.toFixed(2)} on ${forecast.provider}${forecast.format?' · '+forecast.format:''}, roughly ${formatFilmDate(forecast.start)} to ${formatFilmDate(forecast.end)}. Based on ${forecast.samples} other films with comparable store/format price checks. Dates are observations, not exact change times.`+(forecast.overdue?' Estimate window passed; no drop verified.':''),'Estimate');else row('Cheaper rental','No announced reduction date. '+(quotes.length?'Price history does not yet support a date estimate.':'No current price quote to compare.'),'Unknown');}
  const history=(movie.priceHistory||[]).filter(r=>r.kind==='rent').slice(-8);if(history.length){const h=document.createElement('h4');h.textContent='Your recent rental checks';root.appendChild(h);for(const r of history)appendNote(root,`${new Date(r.at).toLocaleDateString('en-US',{month:'short',day:'numeric'})} · ${r.provider}${r.format?' · '+r.format:''} · $${r.price.toFixed(2)}`);}
  if(status.datesUnavailable)appendNote(root,'Release dates could not be refreshed. Previous dates may have changed.','lookup-warning');
  if(status.announcementUnavailable)appendNote(root,'Announcement feed could not be refreshed.','lookup-warning');
  if(status.calendarWarning)appendNote(root,status.calendarWarning);
  appendNote(root,'Selected verified announcements, not a complete streaming calendar. Estimates never trigger an email.');
  return root;
}

function renderReleaseTimeline(movie,status,context={}){
 const root=document.createElement('section');root.className='visual-release';const today=discoveryWindow().today,stage=ReleaseModel.stages(status.details||movie.detailsSnapshot,today),points=[];
 const add=(label,date,certainty,source)=>{points.push({label,date:ReleaseModel.date(date)?date.slice(0,10):null,certainty,source});};
 if(stage.wide||stage.limited)add('Theaters',stage.wide||stage.limited,'Listed');
 const digital=(status.announcements||[]).find(a=>a.kind==='digital');if(digital?.date||stage.digital)add('Rent / buy',digital?.date||stage.digital,digital?'Announced':'Listed',digital?.sourceUrl);
 else if((status.offers||[]).some(o=>['rent','buy'].includes(o.kind)))add('Rent / buy',null,'Available now');
 else {const e=ReleaseModel.digitalEstimate(status.details||movie.detailsSnapshot||{},context.details||[],today);if(e&&!e.overdue)add('Digital window',e.start,'Estimate · through '+formatFilmDate(e.end));else add('Digital',null,'Not announced');}
 const subscriptions=(status.announcements||[]).filter(a=>a.kind==='subscription');for(const a of subscriptions)add(a.provider,a.date,'Announced',a.sourceUrl);
 for(const c of status.calendar||[]){if(c.region&&c.region!=='US'||!c.source_name||!ReleaseModel.date(c.source_release_date)||subscriptions.some(a=>a.provider===c.source_name&&a.date===c.source_release_date))continue;add(c.source_name,c.source_release_date,'Listed');}
 const included=[...new Set((status.offers||[]).filter(o=>o.kind==='subscription'&&o.included).map(o=>o.provider))];if(included.length)add(included.join(' / '),null,status.stale?'Previous check':'Streaming now');else if(!subscriptions.length&&!points.some(p=>p.label!=='Theaters'&&p.label!=='Rent / buy'&&p.label!=='Digital'&&p.label!=='Digital window'))add('Subscription',null,'Not announced');
 const price=(status.announcements||[]).find(a=>a.kind==='price'&&typeof a.price==='number');if(price)add('$'+price.price.toFixed(2)+' rental',price.date,'Announced',price.sourceUrl);else {const e=ReleaseModel.priceEstimate(movie,status.offers,context.movies||[],today,rentalBudget);if(e&&!e.overdue)add('Under $'+e.threshold.toFixed(2),e.start,'Estimate · through '+formatFilmDate(e.end));}
 const dated=points.filter(p=>p.date).sort((a,b)=>a.date.localeCompare(b.date)),undated=points.filter(p=>!p.date);
 if(dated.length){const line=document.createElement('div');line.className='release-graphic';line.setAttribute('aria-label','Release timeline. Spacing follows the listed dates.');const min=Math.min(...dated.map(p=>Date.parse(p.date))),max=Math.max(Date.parse(today),...dated.map(p=>Date.parse(p.date))),span=Math.max(86400000,max-min);line.style.height=(80+dated.length*35)+'px';const rail=document.createElement('div');rail.className='release-rail';line.appendChild(rail);
 for(const [i,p] of dated.entries()){const dot=document.createElement('div');dot.className='release-stop '+(p.certainty.startsWith('Estimate')?'estimate':'')+(p.date>today?' future':'');dot.style.left=(5+(Date.parse(p.date)-min)/span*85)+'%';dot.style.top='16px';const text=document.createElement('div');text.className='release-stop-label';text.style.top=(20+i*35)+'px';if((Date.parse(p.date)-min)/span<.45){text.style.left='0';text.style.right='auto';text.style.textAlign='left';}text.textContent=p.label+' · '+formatFilmDate(p.date);const note=document.createElement('small');note.textContent=p.certainty;text.appendChild(note);dot.appendChild(text);line.appendChild(dot);}
 const now=document.createElement('span');now.className='release-today';now.style.left=(5+Math.max(0,Math.min(1,(Date.parse(today)-min)/span))*85)+'%';now.textContent='TODAY';line.appendChild(now);root.appendChild(line);}
 const chips=document.createElement('div');chips.className='release-chips';for(const p of undated){const chip=document.createElement('div');chip.className='release-chip';const label=document.createElement('strong');label.textContent=p.label;const caption=document.createElement('span');caption.textContent=p.certainty;chip.append(label,caption);chips.appendChild(chip);}root.appendChild(chips);return root;
}
