(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory();else root.DiscoveryModel=factory();})(typeof globalThis!=='undefined'?globalThis:this,function(){
 const valid=d=>typeof d==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(d)&&Number.isFinite(Date.parse(d+'T12:00:00Z'))&&new Date(d+'T12:00:00Z').toISOString().slice(0,10)===d;
 function dates(details,types){return (details?.release_dates?.results?.find(r=>r.iso_3166_1==='US')?.release_dates||[]).filter(r=>types.includes(r.type)&&valid(r.release_date?.slice(0,10))).map(r=>({date:r.release_date.slice(0,10),type:r.type,note:r.note||''})).sort((a,b)=>a.date.localeCompare(b.date));}
 function futureMovie(movie,details,today,end){if(!details||details.adult||details.runtime&&details.runtime<60)return null;const us=dates(details,[2,3]).find(r=>r.date>=today&&r.date<=end),world=details.release_date||movie.release_date;if(!us&&!(valid(world)&&world>=today&&world<=end))return null;return {...movie,...details,director:(details.credits?.crew||[]).filter(c=>c.job==='Director').map(c=>c.name).join(', '),genre_ids:(details.genres||[]).map(g=>g.id),releaseFile:{origin:'catalog',stage:us?'announced':'premiere',date:us?.date||world,dateScope:us?'US theatrical listing':'First release listing; US date not established',details:{id:details.id,runtime:details.runtime,release_dates:details.release_dates}}};}
 function sourceMovie(row){if(!row||typeof row.title!=='string'||!row.sourceURL?.startsWith('https://'))return null;return {...row,releaseFile:{origin:'source',stage:row.sourceStatus,source:row.source,sourceURL:row.sourceURL,checkedAt:row.checkedAt,sourceNote:row.sourceNote,news:row.news||[],releaseSources:row.releaseSources||[],stale:!!row.stale,screenings:row.screenings||[],details:row.details}};}
 function facts(movie,status,today){const file=movie.releaseFile||{},details=status?.details||file.details,us=dates(details,[2,3]),next=us.find(r=>r.date>=today),past=us.filter(r=>r.date<today).at(-1),digital=dates(details,[4]).find(r=>r.date>=today),offers=status?.stale?[]:status?.offers||[];
 const home=offers.some(o=>['free','subscription','rent','buy'].includes(o.kind))?'US viewing options listed':digital?'US digital date listed: '+digital.date:status?.stale?'US viewing check unavailable':'No US home date listed';
 const theatrical=next?'US theaters listed: '+next.date:past?(past.type===2?'Limited US run began: ':'US run began: ')+past.date:file.date?file.dateScope+': '+file.date:file.stage==='limited'?'Distributor lists a theatrical run':file.stage==='digital'?'Distributor lists a digital release':file.stage==='physical'?'Distributor lists a physical release':file.stage==='news'?file.sourceNote:file.stage==='announced'?file.sourceNote||'No US theatrical date listed':'No US theatrical date listed';
 const screening=(file.screenings||[]).filter(r=>valid(r.date)&&r.date>=today).sort((a,b)=>a.date.localeCompare(b.date))[0];
 return {theatrical,home,screening,badge:next?'COMING SOON':file.stage==='premiere'?'FIRST RELEASE LISTED':past?.type===2||file.stage==='limited'?'LIMITED RUN':file.stage==='digital'?'DIGITAL LISTED':file.stage==='physical'?'PHYSICAL LISTED':file.stage==='news'?'RELEASE NEWS':file.stage==='announced'?'ANNOUNCED':'ON THE CIRCUIT'};
 }
 return {valid,dates,futureMovie,sourceMovie,facts};
});
