(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.HubModel=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
 const norm=s=>String(s||'').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]/g,'');
 function cleanEventTitle(t){return String(t||'').replace(/^Guillermo del Toro[’']s\s+/i,'').replace(/\s+\d+(?:st|nd|rd|th) Anniversary.*$/i,'').replace(/\s*[–—-]\s*Studio Ghibli Fest.*$/i,'').replace(/\s*\(20\d{2}\)$/,'').trim();}
 function matchEvent(event,movie){const title=norm(cleanEventTitle(event.title)),target=norm(movie.title);if(!title||title!==target)return false;const anniversary=String(event.title||'').match(/(\d+)(?:st|nd|rd|th) Anniversary/i),releaseYear=Number(String(movie.release_date||'').slice(0,4)),eventYear=Number(String(event.start||'').slice(0,4));if(anniversary&&releaseYear&&eventYear&&Math.abs(eventYear-Number(anniversary[1])-releaseYear)>1)return false;return true;}
 function safeLink(value){try{const u=new URL(value);return u.protocol==='https:'&&!u.username&&!u.password?u.href:null;}catch{return null;}}
 function letterboxd(movie){const saved=safeLink(movie.letterboxdURL);if(saved&&['boxd.it','letterboxd.com','www.letterboxd.com'].includes(new URL(saved).hostname))return saved;return 'https://letterboxd.com/tmdb/'+encodeURIComponent(movie.id)+'/';}
 function mergeRecords(existing,incoming){const map=new Map((existing||[]).map(m=>[Number(m.id),m]));for(const item of incoming||[]){if(!Number.isInteger(Number(item.id))||Number(item.id)<=0)continue;const old=map.get(Number(item.id));map.set(Number(item.id),{...old,...item,id:Number(item.id),rewatches:Math.max(old?.rewatches||0,item.rewatches||0),owned:!!(old?.owned||item.owned),physicalFormats:[...new Set([...(old?.physicalFormats||[]),...(item.physicalFormats||[])])]});}return [...map.values()];}
 function evidence(records){return (records||[]).filter(m=>Number(m.rating)>=4||m.owned||m.rewatches>1||m.favorite);}
 const genericKeywords=new Set(['sequel','prequel','reboot','remake','witty','depressing','feel-good','supernatural','murder','death','violence','friendship','family','based on novel or book','based on comic','based on comic book','comic book','duringcreditsstinger','aftercreditsstinger','based on video game']);
 function features(m){const d=m.meta||m;return {genres:(d.genres||[]).map(g=>typeof g==='string'?g:g.name),keywords:(d.keywords?.keywords||d.keywords_full||[]).map(g=>typeof g==='string'?g:g.name).filter(k=>!genericKeywords.has(String(k).toLowerCase())),directors:(d.credits?.crew||[]).filter(c=>c.job==='Director').map(c=>c.name),writers:[...new Set((d.credits?.crew||[]).filter(c=>['Writer','Screenplay','Story'].includes(c.job)).map(c=>c.name))]};}
 function affinity(movie,seeds){const f=features(movie);let best=0,reasons=[];for(const seed of seeds||[]){if(seed.id===movie.id)continue;const s=features(seed),directors=f.directors.filter(x=>s.directors.includes(x)),keywords=f.keywords.filter(x=>s.keywords.includes(x)),writers=f.writers.filter(x=>s.writers.includes(x)),genres=f.genres.filter(x=>s.genres.includes(x));const strength=(Number(seed.rating)>=4?(Number(seed.rating)-3)*0.6:0)+(seed.owned?0.5:0)+(seed.rewatches>1?0.4:0)+(seed.favorite?0.5:0);const score=(directors.length*3+Math.min(2,writers.length)*2+Math.min(4,keywords.length)*1.1+Math.min(2,genres.length)*0.25)*(1+strength);if(score>best){best=score;reasons=[directors.length?'Same director as '+seed.title:writers.length?'Same writer as '+seed.title:keywords.length?'Shares '+keywords.slice(0,2).join(' and ')+' with '+seed.title:genres.length?'Shares '+genres.join(' / ')+' with '+seed.title:'',seed.owned?'You own '+seed.title:seed.rewatches>1?'You have watched '+seed.title+' more than once':seed.favorite?seed.title+' is a saved favorite':seed.rating>=4?'You rated '+seed.title+' '+seed.rating+'/5':''].filter(Boolean);}}return {score:best,reasons};}
 function ranked(candidates,seeds){return candidates.map(m=>({...m,fit:affinity(m,seeds)})).sort((a,b)=>b.fit.score-a.fit.score||a.title.localeCompare(b.title));}
 function roulettePass(m,opts={}){const tags=(m.tags||[]).join(' '),tone=m.tones||{};if(opts.maxRuntime&&(!m.runtime||m.runtime>opts.maxRuntime))return false;if(opts.genre&&!(m.genre_ids||[]).includes(Number(opts.genre)))return false;if(opts.theme&&opts.theme!=='all'&&!tags.includes(opts.theme))return false;if(opts.noGore&&(/\bgore\b|extreme-gore/.test(tags)||!m.tags?.length))return false;if(opts.noSV&&(/sexual-violence|\bsv\b/.test(tags)||!m.tags?.length))return false;if(opts.noKids&&(/kids-in-peril|\bkids\b/.test(tags)||!m.tags?.length))return false;if(opts.preset==='cozy'&&!(tone.cozy>=50&&!/gore|sexual-violence/.test(tags)))return false;if(opts.preset==='folk'&&!/folk|witch/.test(tags))return false;if(opts.preset==='midnight'&&!/cult|neon|body|found|witch|gore/.test(tags))return false;return true;}
 function rouletteWeight(m,target,variety='medium'){const t=m.tones||{},sum=(t.cursed||0)+(t.spooky||0)+(t.cozy||0)||1,ts=(target.cursed||0)+(target.spooky||0)+(target.cozy||0)||1;const dist=Math.sqrt(['cursed','spooky','cozy'].reduce((s,k)=>s+((t[k]||0)/sum-(target[k]||0)/ts)**2,0));const band={tight:0.18,medium:0.32,wide:0.55}[variety]||0.32;return Math.exp(-0.5*(dist/band)**2);}
 function weightedPick(pool,weight,random=Math.random){if(!pool.length)return null;const weights=pool.map(m=>Math.max(0,weight(m)||0)),sum=weights.reduce((a,b)=>a+b,0);if(!sum)return pool[Math.floor(random()*pool.length)];let n=random()*sum;for(let i=0;i<pool.length;i++){n-=weights[i];if(n<=0)return pool[i];}return pool.at(-1);}
 function upcoming(movie,today){const status=movie.availabilitySnapshot||{},rows=[];for(const a of status.announcements||[])if(a.date>=today)rows.push({movie,date:a.date,label:a.provider?'Arrives on '+a.provider:'Digital release',certainty:'Announced',url:a.sourceUrl||a.sourceURL||a.url});for(const a of status.calendar||[]){const date=a.source_release_date?.slice(0,10);if(date>=today)rows.push({movie,date,label:'Arrives on '+a.source_name,certainty:'Listed'});}for(const r of status.details?.release_dates?.results?.find(r=>r.iso_3166_1==='US')?.release_dates||[]){const date=r.release_date?.slice(0,10);if(date>=today&&[2,3,4].includes(r.type))rows.push({movie,date,label:r.type===4?'Digital release':'US theatrical release',certainty:'Listed'});}return [...new Map(rows.map(r=>[r.date+'|'+r.label,r])).values()].sort((a,b)=>a.date.localeCompare(b.date));}
 return {norm,cleanEventTitle,matchEvent,safeLink,letterboxd,mergeRecords,evidence,features,affinity,ranked,roulettePass,rouletteWeight,weightedPick,upcoming};
});
