(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.HubModel=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
 const norm=s=>String(s||'').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]/g,'');
 function cleanEventTitle(t){return String(t||'').replace(/^Guillermo del Toro[’']s\s+/i,'').replace(/\s+\d+(?:st|nd|rd|th) Anniversary.*$/i,'').replace(/\s*[–—-]\s*Studio Ghibli Fest.*$/i,'').replace(/\s*\(20\d{2}\)$/,'').replace(/:\s*Encore$/i,'').replace(/\s+Special Screening$/i,'').trim();}
 function matchEvent(event,movie){const title=norm(cleanEventTitle(event.title)),target=norm(movie.title);if(!title||title!==target)return false;const anniversary=String(event.title||'').match(/(\d+)(?:st|nd|rd|th) Anniversary/i),releaseYear=Number(String(movie.release_date||'').slice(0,4)),eventYear=Number(String(event.start||'').slice(0,4));if(anniversary&&releaseYear&&eventYear&&Math.abs(eventYear-Number(anniversary[1])-releaseYear)>1)return false;return true;}
 function safeLink(value){try{const u=new URL(value);return u.protocol==='https:'&&!u.username&&!u.password?u.href:null;}catch{return null;}}
 function letterboxd(movie){const saved=safeLink(movie.letterboxdURL);if(saved&&['boxd.it','letterboxd.com','www.letterboxd.com'].includes(new URL(saved).hostname))return saved;return 'https://letterboxd.com/tmdb/'+encodeURIComponent(movie.id)+'/';}
 function mergeRecords(existing,incoming){const map=new Map((existing||[]).map(m=>[Number(m.id),m]));for(const item of incoming||[]){if(!Number.isInteger(Number(item.id))||Number(item.id)<=0)continue;const old=map.get(Number(item.id));map.set(Number(item.id),{...old,...item,id:Number(item.id),rewatches:Math.max(old?.rewatches||0,item.rewatches||0),owned:!!(old?.owned||item.owned),physicalFormats:[...new Set([...(old?.physicalFormats||[]),...(item.physicalFormats||[])])]});}return [...map.values()];}
 function evidence(records){return (records||[]).filter(m=>Number(m.rating)>=4||m.owned||m.rewatches>1||m.favorite);}
 const genericKeywords=new Set(['sequel','prequel','reboot','remake','witty','depressing','feel-good','supernatural','murder','death','violence','friendship','family','based on novel or book','based on comic','based on comic book','comic book','duringcreditsstinger','aftercreditsstinger','based on video game','based on myths, legends or folklore','myth','legend','folklore','good versus evil','hero','battle','religion','christianity','bible','faith','hope','redemption']);
 function features(m){const d=m.meta||m;return {genres:(d.genres||[]).map(g=>typeof g==='string'?g:g.name),keywords:(d.keywords?.keywords||d.keywords_full||[]).map(g=>typeof g==='string'?g:g.name).filter(k=>!genericKeywords.has(String(k).toLowerCase())),directors:(d.credits?.crew||[]).filter(c=>c.job==='Director').map(c=>c.name),writers:[...new Set((d.credits?.crew||[]).filter(c=>['Writer','Screenplay','Story'].includes(c.job)).map(c=>c.name))]};}
 function affinity(movie,seeds,feedback=[]){const f=features(movie);let best=0,reasons=[],connection=null;for(const seed of seeds||[]){if(seed.id===movie.id||feedback.some(r=>r.kind==='weak'&&r.id===movie.id&&(r.seedId===seed.id||!r.seedId&&r.seedTitle===seed.title)))continue;const s=features(seed),directors=f.directors.filter(x=>s.directors.includes(x)),keywords=f.keywords.filter(x=>s.keywords.includes(x)),writers=f.writers.filter(x=>s.writers.includes(x)),genres=f.genres.filter(x=>s.genres.includes(x));const strength=(Number(seed.rating)>=4?(Number(seed.rating)-3)*0.6:0)+(seed.owned?0.5:0)+(seed.rewatches>1?0.4:0)+(seed.favorite?0.5:0);const score=(directors.length*3+Math.min(2,writers.length)*2+Math.min(4,keywords.length)*1.1+Math.min(2,genres.length)*0.25)*(1+strength);if(score>best){best=score;connection={seedId:seed.id,seedTitle:seed.title,directors,writers,keywords,genres,rating:seed.rating,owned:!!seed.owned,rewatches:seed.rewatches||0,favorite:!!seed.favorite};reasons=[directors.length?'Same director as '+seed.title:writers.length?'Same writer as '+seed.title:keywords.length?'Shares '+keywords.slice(0,2).join(' and ')+' with '+seed.title:genres.length?'Shares '+genres.join(' / ')+' with '+seed.title:'',seed.owned?'You own '+seed.title:seed.rewatches>1?'You have watched '+seed.title+' more than once':seed.favorite?seed.title+' is a saved favorite':seed.rating>=4?'You rated '+seed.title+' '+seed.rating+'/5':''].filter(Boolean);}}return {score:best,reasons,connection};}
 function ranked(candidates,seeds,feedback=[]){return candidates.map(m=>({...m,fit:affinity(m,seeds,feedback)})).sort((a,b)=>b.fit.score-a.fit.score||a.title.localeCompare(b.title));}
 function roulettePass(m,opts={}){const tags=(m.tags||[]).join(' '),tone=m.tones||{};if(opts.maxRuntime&&(!m.runtime||m.runtime>opts.maxRuntime))return false;if(opts.genre&&!(m.genre_ids||[]).includes(Number(opts.genre)))return false;if(opts.theme&&opts.theme!=='all'&&!tags.includes(opts.theme))return false;if(opts.noGore&&(/\bgore\b|extreme-gore/.test(tags)||!m.tags?.length))return false;if(opts.noSV&&(/sexual-violence|\bsv\b/.test(tags)||!m.tags?.length))return false;if(opts.noKids&&(/kids-in-peril|\bkids\b/.test(tags)||!m.tags?.length))return false;if(opts.preset==='cozy'&&!(tone.cozy>=50&&!/gore|sexual-violence/.test(tags)))return false;if(opts.preset==='folk'&&!/folk|witch/.test(tags))return false;if(opts.preset==='midnight'&&!/cult|neon|body|found|witch|gore/.test(tags))return false;return true;}
 function rouletteWeight(m,target,variety='medium'){const t=m.tones||{},sum=(t.cursed||0)+(t.spooky||0)+(t.cozy||0)||1,ts=(target.cursed||0)+(target.spooky||0)+(target.cozy||0)||1;const dist=Math.sqrt(['cursed','spooky','cozy'].reduce((s,k)=>s+((t[k]||0)/sum-(target[k]||0)/ts)**2,0));const band={tight:0.18,medium:0.32,wide:0.55}[variety]||0.32;return Math.exp(-0.5*(dist/band)**2);}
 function weightedPick(pool,weight,random=Math.random){if(!pool.length)return null;const weights=pool.map(m=>Math.max(0,weight(m)||0)),sum=weights.reduce((a,b)=>a+b,0);if(!sum)return pool[Math.floor(random()*pool.length)];let n=random()*sum;for(let i=0;i<pool.length;i++){n-=weights[i];if(n<=0)return pool[i];}return pool.at(-1);}
 function upcoming(movie,today){
  const status=movie.availabilitySnapshot||{},rows=[];
  for(const a of status.announcements||[]){
    if(!a.date||a.date<today||a.kind==='price')continue;
    const theatrical=a.kind==='theatrical',platform=theatrical?null:(a.provider||null);
    rows.push({movie,date:a.date,label:theatrical?'US theatrical release':platform?'Arrives on '+platform:'Digital release',theatrical,platform,sourceKind:'announcement',announcementKind:a.kind||'digital',certainty:'Announced',url:a.sourceUrl||a.sourceURL||a.url});
  }
  for(const a of status.calendar||[]){
    const date=a.source_release_date?.slice(0,10);
    if(date>=today)rows.push({movie,date,label:a.source_name?'Arrives on '+a.source_name:'Digital release',theatrical:false,platform:a.source_name||null,sourceKind:'watchmode',certainty:'Listed'});
  }
  for(const r of (status.details||movie.releaseFile?.details)?.release_dates?.results?.find(r=>r.iso_3166_1==='US')?.release_dates||[]){
    const date=r.release_date?.slice(0,10);
    if(date>=today&&[2,3,4].includes(r.type))rows.push({movie,date,label:r.type===4?'Digital release':'US theatrical release',theatrical:r.type!==4,platform:null,sourceKind:'tmdb',certainty:'Listed'});
  }
  for(const r of movie.releaseFile?.screenings||[])if(r.date>=today&&Number.isFinite(r.checkedAt)&&Date.now()-r.checkedAt<7*86400000)rows.push({movie,date:r.date,label:r.label+' · '+r.location+' · '+r.time+' MT',theatrical:true,sourceKind:'regional',certainty:r.stale?'Previous check':'Listed regional screening',url:safeLink(r.sourceURL),regional:true,stale:!!r.stale});
  // A verified provider listing supersedes a generic digital date for the same day.
  const specificDates=new Set(rows.filter(r=>r.platform&&!r.theatrical).map(r=>r.date));
  return [...new Map(rows.filter(r=>!(r.sourceKind==='tmdb'&&!r.theatrical&&specificDates.has(r.date))).map(r=>[r.date+'|'+r.label,r])).values()].sort((a,b)=>a.date.localeCompare(b.date));
 }
 function isIncluded(status){return !status?.stale&&(status?.offers||[]).some(o=>o.kind==='free'||o.kind==='subscription'&&o.included);}
 function watchlistPriority(movie,at=Date.now()){const arrived=Number(movie.includedSince),age=at-arrived;return (movie.pinned?2:0)+(arrived>0&&age>=0&&age<=14*86400000&&isIncluded(movie.availabilitySnapshot)?1:0);}
 function shuffle(items,random=Math.random){const copy=[...items];for(let i=copy.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[copy[i],copy[j]]=[copy[j],copy[i]];}return copy;}
 function orderWatchlist(items,mode='smart',at=Date.now(),random=Math.random){const copy=shuffle(items,random);return mode==='shuffle'?copy:copy.sort((a,b)=>watchlistPriority(b,at)-watchlistPriority(a,at));}

 function shelfStatus(movie){const offers=(movie.physicalFormats?.length?movie.physicalFormats:['Physical copy']).map(format=>({kind:'physical',provider:'Your shelf',format,included:true,price:0,link:null}));return {offers,physical:true,code:'owned',kind:'physical',label:'On your physical shelf',stale:false};}
 function theaterIdentity(event,film){return {listingId:event.id||null,id:film?.id||null,title:cleanEventTitle(event.title),year:String(film?.release_date||'').slice(0,4)};}
 function sameTheaterFilm(a,b){if(a.listingId&&b.listingId&&a.listingId===b.listingId)return true;if(a.id&&b.id)return Number(a.id)===Number(b.id);return norm(a.title)===norm(b.title)&&(!a.year||!b.year||a.year===b.year);}
 function strongConnection(fit){const c=fit?.connection;return !!c&&fit.score>=3&&(c.directors.length>0||c.writers.length>0||c.keywords.length>=2);}
 function shelfRow(raw){const row=Object.fromEntries(Object.entries(raw).map(([k,v])=>[k.toLowerCase().replace(/[^a-z0-9]/g,''),v]));return {title:row.name||row.title||row.movietitle||row.filmtitle,year:String(row.year||row.releaseyear||row.productionyear||'').slice(0,4),format:row.format||row.mediaformat||row.mediatype||row.media||row.type||'Physical copy',tmdbId:row.tmdbid};}
 return {strongConnection,shelfStatus,theaterIdentity,sameTheaterFilm,shelfRow,norm,cleanEventTitle,matchEvent,safeLink,letterboxd,mergeRecords,evidence,features,affinity,ranked,roulettePass,rouletteWeight,weightedPick,upcoming,isIncluded,watchlistPriority,shuffle,orderWatchlist};
});
