(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.OccasionModel=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
 const valid=d=>typeof d==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(d)&&Number.isFinite(Date.parse(d+'T12:00:00Z'))&&new Date(d+'T12:00:00Z').toISOString().slice(0,10)===d;
 const localDate=at=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Denver',year:'numeric',month:'2-digit',day:'2-digit'}).format(at);
 function events(films,snapshot,year,month){const out=[],dateFor=d=>{if(!valid(d)||Number(d.slice(5,7))!==month+1||Number(d.slice(0,4))>=year)return null;const date=year+d.slice(4);return valid(date)?date:null;};
  for(const movie of [...new Map(films.filter(m=>m.id).map(m=>[m.id,m])).values()]){const date=dateFor(movie.release_date);if(!date)continue;const years=year-Number(movie.release_date.slice(0,4));out.push({date,kind:'anniversary',title:movie.title,label:years+' years since first release',years,original:movie.release_date,movie,sourceURL:'https://www.themoviedb.org/movie/'+movie.id+'/releases',imageURL:movie.poster_path?'https://image.tmdb.org/t/p/w185'+movie.poster_path:null,weight:(movie.owned?4:0)+(movie.favorite?3:0)+(movie.rating||0)+(years%10===0?3:years%5===0?1:0)});}
  for(const person of snapshot?.people||[]){const date=dateFor(person.birthday);if(!date)continue;out.push({date,kind:'birthday',title:person.name,label:'Born '+person.birthday.slice(0,4),original:person.birthday,person,sourceURL:person.sourceURL,imageURL:person.imageURL||(person.profile_path?'https://image.tmdb.org/t/p/w185'+person.profile_path:null),weight:9});}
  for(const day of snapshot?.days||[]){const date=year+'-'+String(day.month).padStart(2,'0')+'-'+String(day.day).padStart(2,'0');if(day.month!==month+1||!valid(date))continue;out.push({date,kind:day.kind,title:day.title,label:day.kind==='season'?'Seasonal occasion':'Film culture',sourceURL:day.sourceURL,match:day.match,weight:10});}
  return out.sort((a,b)=>a.date.localeCompare(b.date)||b.weight-a.weight||a.title.localeCompare(b.title));
 }
 function matches(movie,snapshot,at=Date.now()){const date=localDate(at),d=movie.meta||movie,crew=(d.credits?.crew||[]).filter(c=>c.job==='Director'),words=[movie.title,movie.overview,d.overview,...(d.genres||[]).map(g=>g.name||g),...(d.keywords?.keywords||[]).map(k=>k.name||k)].join(' ').toLowerCase();return events([movie],snapshot,Number(date.slice(0,4)),Number(date.slice(5,7))-1).filter(e=>e.date===date&&(e.kind==='anniversary'||e.kind==='birthday'&&(crew.some(c=>c.name===e.person.name||e.person.id!=null&&c.id===e.person.id)||e.person.films.some(m=>m.id===movie.id))||['culture','season'].includes(e.kind)&&new RegExp('\\b(?:'+e.match+')\\b','i').test(words))).sort((a,b)=>({anniversary:0,birthday:1,culture:2,season:2}[a.kind]-{anniversary:0,birthday:1,culture:2,season:2}[b.kind]));}
 function line(movie,occasion){if(occasion.kind==='anniversary')return 'It is also '+occasion.years+' years since '+movie.title+'’s catalog first-release date; the calendar has supplied its own invitation to press play.';if(occasion.kind==='birthday')return occasion.title+' was born on this date, so '+movie.title+' has an additional excuse to take over the room.';return 'It is also '+occasion.title+'; '+movie.title+' gives the occasion something to put on the screen.';}
 return {valid,localDate,events,matches,line};
});
