/* Taste leads. Atmospheric divination is bounded and labeled. No private data leaves the browser. */
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.FilmOracle=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
 function moon(at){const cycle=29.530588853,days=(at-Date.UTC(2000,0,6,18,14))/86400000,phase=((days%cycle)+cycle)%cycle/cycle,names=['New moon','Waxing crescent','First quarter','Waxing gibbous','Full moon','Waning gibbous','Last quarter','Waning crescent'];return {phase,name:names[Math.floor(phase*8+.5)%8],illumination:Math.round((1-Math.cos(phase*Math.PI*2))/2*100)};}
 function rank(movie,fit,context,records,at=Date.now(),local=false){const d=movie.meta||movie,w=context?.weather?.current||{},daily=context?.weather?.daily||{},m=moon(at),clock=new Intl.DateTimeFormat('en-US',{timeZone:'America/Denver',hour:'numeric',hourCycle:'h23',weekday:'long',month:'numeric',day:'numeric'}).formatToParts(at),part=t=>clock.find(p=>p.type===t)?.value,hour=Number(part('hour')),month=Number(part('month')),weekend=['Friday','Saturday'].includes(part('weekday')),genres=(d.genres||[]).map(g=>g.name||g),keywords=(d.keywords?.keywords||[]).map(k=>k.name||k),words=[movie.title,movie.overview,...genres,...keywords].join(' ').toLowerCase(),notes=[],ledger=[],nudge=[];
 const evidence=(title,value,why)=>ledger.push({title,value:String(value),why});let atmospheric=0;
 const push=(score,text)=>{atmospheric+=score;nudge.push(text);};
 evidence('Taste connection',fit?.score>0?'Established':'No strong connection',fit?.reasons?.join('. ')||'No invented personal match.');
 evidence('Temperature',Number.isFinite(w.temperature_2m)?w.temperature_2m+'°F':'Unavailable','Kalispell modeled conditions, not a measurement at your house.');evidence('Feels like',Number.isFinite(w.apparent_temperature)?w.apparent_temperature+'°F':'Unavailable','Wind and humidity folded into the weather model.');
 evidence('Humidity',Number.isFinite(w.relative_humidity_2m)?w.relative_humidity_2m+'%':'Unavailable','High humidity can supply a very small swamp-and-dread nudge.');evidence('Cloud cover',Number.isFinite(w.cloud_cover)?w.cloud_cover+'%':'Unavailable','Overcast conditions favor enclosed, atmospheric settings slightly.');evidence('Rain / snow',Number.isFinite(w.precipitation)?w.precipitation+' inches':'Unavailable','Weather is a tie breaker, not evidence of your taste.');evidence('Wind',Number.isFinite(w.wind_speed_10m)?w.wind_speed_10m+' mph':'Unavailable','Exposed landscapes become marginally more tempting.');evidence('Gusts',Number.isFinite(w.wind_gusts_10m)?w.wind_gusts_10m+' mph':'Unavailable','Consulted for the atmosphere report.');evidence('Air pressure',Number.isFinite(w.pressure_msl)?w.pressure_msl+' hPa':'Unavailable','Sea-level pressure, not Kalispell surface pressure.');evidence('Surface pressure',Number.isFinite(w.surface_pressure)?w.surface_pressure+' hPa':'Unavailable','Recorded for completeness; altitude makes this a poor storm shortcut.');evidence('Daylight',daily.daylight_duration?.[0]!=null?(daily.daylight_duration[0]/3600).toFixed(1)+' hours':'Unavailable','Seasonal light is a small atmosphere input.');evidence('Sunset',daily.sunset?.[0]?.split('T')[1]||'Unavailable','Mountain Time.');evidence('Rain probability',daily.precipitation_probability_max?.[0]!=null?daily.precipitation_probability_max[0]+'%':'Unavailable','Forecast for today, not a claim it is raining.');
 evidence('Moon',m.name+' · '+m.illumination+'% lit','Approximate synodic calculation. Astronomical garnish.');evidence('Local clock',part('weekday')+' · '+hour+':00 hour','America/Denver. Runtime nudges loosen on Friday and Saturday.');evidence('Season',month>=9&&month<=11?'Autumn':month>=6&&month<=8?'Summer':month>=3&&month<=5?'Spring':'Winter','Calendar season, not an emotional diagnosis.');evidence('Runtime',d.runtime?d.runtime+' minutes':'Not supplied','Late weekday picks get a slight short-film preference.');evidence('Release year',(movie.release_date||'').slice(0,4)||'Unknown','A recent watching streak can earn a small era counterweight.');evidence('Genres',genres.join(', ')||'Unknown','Actual movie metadata.');evidence('Keywords',keywords.slice(0,12).join(', ')||'Unavailable','Connected metadata, not invented plot details.');evidence('Local screening',local?'Listed in Kalispell':'No matched current listing','Exact-title calendar match.');
 if(w.temperature_2m<45&&/winter|snow|isolat|mountain|remote/.test(words))push(.22,'Cold outside, isolation inside. The weather has filed a supporting brief.');if(w.relative_humidity_2m>75&&/swamp|body horror|fung|decay|humid/.test(words))push(.18,'The humidity is making a small, unpleasant case for organic horror.');if(w.cloud_cover>70&&/horror|mystery|thriller|noir/.test(words))push(.18,'Cloud cover lends this a little permission to be gloomy.');if(w.precipitation>0&&/rain|storm|sea|ocean/.test(words))push(.2,'Actual precipitation. The watery imagery has an accomplice.');if(w.wind_speed_10m>12&&/desert|landscape|survival|mountain/.test(words))push(.15,'The wind favors a film with exposed terrain.');if(w.pressure_msl<1005&&/thriller|horror/.test(words))push(.12,'Low pressure adds a tiny ominous-weather nudge.');if(month===10&&/horror|witch|supernatural/.test(words))push(.18,'October supplies the least mysterious part of the divination.');if(m.illumination>85&&/werewolf|moon|cosmic|space/.test(words))push(.15,'The bright moon has requested something cosmically irresponsible.');if(w.is_day===0&&/noir|night|dream|surreal/.test(words))push(.15,'Darkness gives the dream logic a slight advantage.');if(!weekend&&hour>=21&&d.runtime&&d.runtime<=105)push(.18,'Late weekday: this one leaves room for sleep.');if(weekend&&d.runtime>=130)push(.12,'Friday or Saturday gives a long film some breathing room.');if(local)push(.25,'A listed local run is a reason to act before the calendar changes.');
 const recent=(records||[]).filter(r=>r.watchedAt&&Number.isFinite(Date.parse(r.watchedAt))).sort((a,b)=>b.watchedAt.localeCompare(a.watchedAt)).slice(0,5);evidence('Recent watches',recent.length?recent.map(r=>r.title).join(', '):'No dated diary records imported','Missing records do not mean you watched nothing.');if(recent.length>=3){const years=recent.map(r=>Number((r.release_date||'').slice(0,4))).filter(Boolean),year=Number((movie.release_date||'').slice(0,4));if(years.length>=3&&years.every(y=>y>=2015)&&year&&year<2000)push(.18,'Your imported recent diary leans new. This opens a door into an older decade.');}
 const headlines=(context?.news||[]),tokens=new Set([...keywords,...genres].join(' ').toLowerCase().match(/[a-z]{5,}/g)||[]),related=headlines.find(n=>[...tokens].some(t=>n.title.toLowerCase().includes(t)));evidence('Recent film news',headlines.length?headlines.length+' dated headlines consulted':'Unavailable','A headline does not prove you care about its subject.');if(related)push(.12,'A current film headline overlaps the metadata: '+related.title);evidence('Inferred atmosphere',nudge.length?nudge.slice(0,2).join(' '):'No atmospheric match strong enough to mention','Playful interpretation of conditions. Your actual mood is unknown.');evidence('Ownership / favorites',records.filter(r=>r.owned||r.favorite).length+' records','Positive signals only.');evidence('Repeat watches',records.filter(r=>r.rewatches>1).length+' records','Repetition counts as affection.');evidence('High ratings',records.filter(r=>r.rating>=4).length+' records','Watchlist additions and silence do not count.');
 return {...movie,fit:fit||{score:0,reasons:[]},oracle:{score:(fit?.score||0)+Math.min(.8,atmospheric),nudge,ledger,related,moon:m,checkedAt:context?.checkedAt||null,verdict:fit?.score>0?'The taste evidence is doing the work. The atmosphere is being dramatic.':'A discovery, with atmospheric tie breakers. No strong personal taste match was established.'}};
 }
 return {moon,rank};
});
