/* Taste leads. Atmospheric divination is bounded and labeled. No private data leaves the browser. */
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.FilmOracle=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
 function moon(at){const cycle=29.530588853,days=(at-Date.UTC(2000,0,6,18,14))/86400000,phase=((days%cycle)+cycle)%cycle/cycle,names=['New moon','Waxing crescent','First quarter','Waxing gibbous','Full moon','Waning gibbous','Last quarter','Waning crescent'];return {phase,name:names[Math.floor(phase*8+.5)%8],illumination:Math.round((1-Math.cos(phase*Math.PI*2))/2*100)};}
 function rank(movie,fit,context,records,at=Date.now(),local=false){const d=movie.meta||movie,w=context?.weather?.current||{},daily=context?.weather?.daily||{},m=moon(at),clock=new Intl.DateTimeFormat('en-US',{timeZone:'America/Denver',hour:'numeric',hourCycle:'h23',weekday:'long',month:'numeric',day:'numeric'}).formatToParts(at),part=t=>clock.find(p=>p.type===t)?.value,hour=Number(part('hour')),month=Number(part('month')),weekend=['Friday','Saturday'].includes(part('weekday')),genres=(d.genres||[]).map(g=>g.name||g),keywords=(d.keywords?.keywords||[]).map(k=>k.name||k),words=[movie.title,movie.overview,...genres,...keywords].join(' ').toLowerCase(),notes=[],ledger=[],nudge=[];
 const evidence=(title,value,why)=>ledger.push({title,value:String(value),why});let atmospheric=0;
 const push=(score,text)=>{atmospheric+=score;nudge.push(text);};
 evidence('Taste connection',fit?.score>0?'Established':'No strong connection',fit?.reasons?.join('. ')||'No invented personal match.');
 evidence('Temperature',Number.isFinite(w.temperature_2m)?w.temperature_2m+'°F':'Unavailable','Kalispell modeled conditions, not a measurement at your house.');evidence('Feels like',Number.isFinite(w.apparent_temperature)?w.apparent_temperature+'°F':'Unavailable','Wind and humidity folded into the weather model.');
 evidence('Humidity',Number.isFinite(w.relative_humidity_2m)?w.relative_humidity_2m+'%':'Unavailable','High humidity can supply a very small swamp-and-dread nudge.');evidence('Cloud cover',Number.isFinite(w.cloud_cover)?w.cloud_cover+'%':'Unavailable','Overcast conditions favor enclosed, atmospheric settings slightly.');evidence('Rain / snow',Number.isFinite(w.precipitation)?w.precipitation+' inches':'Unavailable','Weather is a tie breaker, not evidence of your taste.');evidence('Wind',Number.isFinite(w.wind_speed_10m)?w.wind_speed_10m+' mph':'Unavailable','Exposed landscapes become marginally more tempting.');evidence('Gusts',Number.isFinite(w.wind_gusts_10m)?w.wind_gusts_10m+' mph':'Unavailable','Consulted for the atmosphere report.');evidence('Air pressure',Number.isFinite(w.pressure_msl)?w.pressure_msl+' hPa':'Unavailable','Sea-level pressure, not Kalispell surface pressure.');evidence('Surface pressure',Number.isFinite(w.surface_pressure)?w.surface_pressure+' hPa':'Unavailable','Recorded for completeness; altitude makes this a poor storm shortcut.');evidence('Daylight',daily.daylight_duration?.[0]!=null?(daily.daylight_duration[0]/3600).toFixed(1)+' hours':'Unavailable','Seasonal light is a small atmosphere input.');evidence('Sunset',daily.sunset?.[0]?.split('T')[1]||'Unavailable','Mountain Time.');evidence('Rain probability',daily.precipitation_probability_max?.[0]!=null?daily.precipitation_probability_max[0]+'%':'Unavailable','Forecast for today, not a claim it is raining.');
 evidence('Moon',m.name+' · '+m.illumination+'% lit','Approximate synodic calculation. Astronomical garnish.');evidence('Local clock',part('weekday')+' · '+hour+':00 hour','America/Denver. Runtime nudges loosen on Friday and Saturday.');evidence('Season',month>=9&&month<=11?'Autumn':month>=6&&month<=8?'Summer':month>=3&&month<=5?'Spring':'Winter','Calendar season, not an emotional diagnosis.');evidence('Runtime',d.runtime?d.runtime+' minutes':'Not supplied','Late weekday picks get a slight short-film preference.');evidence('Release year',(movie.release_date||'').slice(0,4)||'Unknown','A recent watching streak can earn a small era counterweight.');evidence('Director',(d.credits?.crew||[]).filter(c=>c.job==='Director').map(c=>c.name).join(', ')||'Unknown','Matched against every connected positive taste record.');evidence('Writers',[...new Set((d.credits?.crew||[]).filter(c=>['Writer','Screenplay','Story'].includes(c.job)).map(c=>c.name))].join(', ')||'Unknown','Writer connections can earn their own recommendation.');evidence('Genres',genres.join(', ')||'Unknown','Actual movie metadata.');evidence('Keywords',keywords.slice(0,12).join(', ')||'Unavailable','Connected metadata, not invented plot details.');evidence('Local screening',local?'Listed in Kalispell':'No matched current listing','Exact-title calendar match.');
 if(w.temperature_2m<45&&/winter|snow|isolat|mountain|remote/.test(words))push(.22,'Kalispell is cold. Let the film take the isolation shift while you keep the heating.');if(w.relative_humidity_2m>75&&/swamp|body horror|fung|decay|humid/.test(words))push(.18,'The air is already damp. A film about organic unpleasantness can meet it halfway.');if(w.cloud_cover>70&&/horror|mystery|thriller|noir/.test(words))push(.18,'Clouds have put a lid on Kalispell. A suspicious film belongs under it.');if(w.precipitation>0&&/rain|storm|sea|ocean/.test(words))push(.2,'It is wet outside. The watery imagery has escaped the screen and reached Montana.');if(w.wind_speed_10m>12&&/desert|landscape|survival|mountain/.test(words))push(.15,'There is wind outside. Let somebody else cross the exposed landscape.');if(w.pressure_msl<1005&&/thriller|horror/.test(words))push(.12,'Low pressure outside; a little dread inside. A dubious pairing, but the Oracle likes it.');if(month===10&&/horror|witch|supernatural/.test(words))push(.18,'It is October. The Oracle is allowed one seasonal lapse in judgment.');if(m.illumination>85&&/werewolf|moon|cosmic|space/.test(words))push(.15,'The moon is unusually bright. An excellent night to give the universe more credit than it deserves.');if(w.is_day===0&&/noir|night|dream|surreal/.test(words))push(.15,'It is dark outside. The dream logic can spread out a little.');if(!weekend&&hour>=21&&d.runtime&&d.runtime<=105)push(.18,'A short film for a late weekday. You can have an experience and still be a functioning mammal tomorrow.');if(weekend&&d.runtime>=130)push(.12,'A long film on a Friday or Saturday. Let it take up unreasonable amounts of the evening.');if(local)push(.25,'It has a listed Kalispell run. The Oracle occasionally believes in leaving the house.');
 const recent=(records||[]).filter(r=>r.watchedAt&&Number.isFinite(Date.parse(r.watchedAt))).sort((a,b)=>b.watchedAt.localeCompare(a.watchedAt)).slice(0,5);evidence('Dated diary records',recent.length?recent.map(r=>r.title).join(', '):'No dated diary records imported','Dates may be backfilled. They do not establish your recent viewing order.');
 const headlines=(context?.news||[]),tokens=new Set([movie.title,...(d.credits?.crew||[]).filter(c=>['Director','Writer','Screenplay'].includes(c.job)).map(c=>c.name)].filter(t=>t&&t.length>=5).map(t=>t.toLowerCase())),related=headlines.find(n=>[...tokens].some(t=>n.title.toLowerCase().includes(t)));evidence('Recent film news',headlines.length?headlines.length+' dated headlines consulted':'Unavailable','A headline does not prove you care about its subject.');if(related)push(.12,'A current film headline names this film or one of its creators: '+related.title);evidence('Inferred atmosphere',nudge.length?nudge.slice(0,2).join(' '):'No atmospheric match strong enough to mention','Playful interpretation of conditions. Your actual mood is unknown.');evidence('Ownership / favorites',records.filter(r=>r.owned||r.favorite).length+' records','Positive signals only.');evidence('Repeat watches',records.filter(r=>r.rewatches>1).length+' records','Repetition counts as affection.');evidence('High ratings',records.filter(r=>r.rating>=4).length+' records','Watchlist additions and silence do not count.');
 return {...movie,fit:fit||{score:0,reasons:[]},oracle:{score:(fit?.score||0)+Math.min(.8,atmospheric),nudge,ledger,related,moon:m,checkedAt:context?.checkedAt||null,verdict:fit?.score>0?'The taste evidence is doing the work. The atmosphere is being dramatic.':'A discovery, with atmospheric tie breakers. No strong personal taste match was established.'}};
 }
 function reading(movie,fit,at=Date.now()){
  const d=movie.meta||movie,keywords=(d.keywords?.keywords||[]).map(k=>k.name||k),genres=(d.genres||[]).map(g=>g.name||g),words=[...keywords,...genres,movie.overview||''].join(' ').toLowerCase();
  const cases=[
   [/undercover|police|espionage|spy|crime/, 'Trust absolutely nobody.', ['Tonight calls for a film that makes a man introducing himself feel like a threat. By the end, you should distrust the haircut, the handshake, and the second phone.', 'An evening of lies, divided loyalties, and people who should have chosen a less complicated occupation. The Oracle has checked everyone’s references. They are also lies.']],
   [/body horror|mutat|fung|parasite|decay/, 'The body has other plans.', ['Something unpleasant for the part of your brain that keeps asking whether skin is really necessary. The Oracle suggests eating first.', 'A little organic unpleasantness. Flesh making decisions without consulting its owner. Put the snacks somewhere you cannot see them.']],
   [/found footage|mockumentary|surveillance|videotape/, 'Someone should have stopped recording.', ['For the pleasure of watching a recording become a very bad idea. Every recovered tape is, at some level, a customer complaint from beyond the grave.', 'An artifact from the department of things that should have stayed in a box. The Oracle has pressed play. Naturally, nobody has checked the box.']],
   [/cosmic|space|alien|extraterrestrial/, 'The universe is being rude again.', ['Something with enough scale to make the room feel briefly inadequate. A whole indifferent universe, delivered to the couch.', 'Tonight’s modest proposal: consider how enormous everything is, then become concerned about a noise in the kitchen.']],
   [/surreal|dream|hallucinat|experimental/, 'The exits have been rearranged.', ['A film for the pleasure of losing your bearings on purpose. Leave one lamp on. It will not explain anything, but it can stand there looking useful.', 'Tonight, ordinary reality can wait in the car. The Oracle has brought you something with a less cooperative floor plan.']],
   [/isolation|isolated|remote|snow|winter|mountain/, 'The nearest neighbor is too far away.', ['Let the landscape do some of the threatening. A room, a long distance, and the growing suspicion that the long distance was the point.', 'Something spacious enough for silence to start behaving badly. The Oracle would prefer that you stayed comfortably indoors for this experiment.']],
   [/grief|bereave|memory|memories|loss|mourning/, 'A small object. An enormous feeling.', ['For when a film gets its hands on some ordinary little thing and makes it impossible to look at normally again. Emotional damage, administered through household objects.', 'Something that may leave a perfectly normal room feeling recently abandoned. The Oracle recommends allowing the credits to finish.']],
   [/witch|folk horror|ritual|cult/, 'Do not join the local committee.', ['A little ritual, a little community, a terrible reason to accept an invitation. The Oracle has declined the potluck on your behalf.', 'For the ancient human terror of arriving somewhere picturesque and discovering that everyone already knows your name.']],
   [/romance|romantic|love affair/, 'Two people. Several avoidable problems.', ['The Oracle has selected a film about the catastrophic administrative consequences of wanting somebody. Very little can be solved by being sensible.', 'Some tenderness, with the usual risk of someone saying the wrong thing at the only moment it mattered.']],
   [/comedy/, 'There is no dignified way through this.', ['A film for watching somebody’s bad idea become everybody’s afternoon. The Oracle respects a disaster that commits to the bit.', 'Tonight’s offering concerns the human animal and its apparently unlimited capacity to make things worse. At least it has the decency to be funny.']],
   [/horror|thriller|mystery/, 'The room is probably fine.', ['A controlled deterioration of the evening. The Oracle recommends a familiar room, a working lamp, and absolutely no investigation of that noise.', 'For the pleasure of feeling something is wrong before anyone can explain what. You can remain on the couch. The people in the film have made other arrangements.']],
   [/drama/, 'Let somebody else’s life get complicated.', ['A film that gives ordinary human decisions room to become enormous. The Oracle would like you to leave a little space after the credits.', 'People wanting things, saying things, and discovering that neither activity comes with an Undo button. The Oracle has concerns. It is pressing play anyway.']]
  ];
  const chosen=cases.find(([pattern])=>pattern.test(words)),variant=(Number(movie.id)||0)%2;
  const heading=chosen?chosen[1]:'A door you have not opened.';
  let text=chosen?chosen[2][variant]:'The Oracle has pulled this one out of the stack. The personal case is thin; curiosity gets to make a decision occasionally.';
  const c=fit?.connection;
  if(c&&fit.score>0){
   const affection=c.owned?'You have '+c.seedTitle+' on your shelf.':c.rewatches>1?'You went back to '+c.seedTitle+'.':c.favorite?c.seedTitle+' is one of your saved favorites.':c.rating>=4?'You gave '+c.seedTitle+' '+c.rating+'/5.':'';
   if(c.directors.length)text+=' '+affection+' This comes from '+c.directors.join(' and ')+'. The Oracle is following the person who made the previous mess.';
   else if(c.writers.length)text+=' '+affection+' '+c.writers.join(' and ')+' wrote both. Return to the source of the trouble.';
   else if(c.keywords.length)text+=' '+affection+' There is a trail from that film to this one. The actual clues are in the drawer below.';
   else text+=' '+affection+' That is a loose genre connection, so the Oracle is leaving room to be wrong.';
  }
  return {heading,text};
 }
 return {moon,rank,reading};
});
