/* Taste leads. Atmospheric divination is bounded and labeled. Ranking stays local; optional prose uses the built-in written profile. */
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.FilmOracle=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
 function moon(at){const cycle=29.530588853,days=(at-Date.UTC(2000,0,6,18,14))/86400000,phase=((days%cycle)+cycle)%cycle/cycle,names=['New moon','Waxing crescent','First quarter','Waxing gibbous','Full moon','Waning gibbous','Last quarter','Waning crescent'];return {phase,name:names[Math.floor(phase*8+.5)%8],illumination:Math.round((1-Math.cos(phase*Math.PI*2))/2*100)};}
 function rank(movie,fit,context,records=[],at=Date.now(),local=false){
 const d=movie.meta||movie,w=context?.weather?.current||{},daily=context?.weather?.daily||{},m=moon(at),parts=new Intl.DateTimeFormat('en-US',{timeZone:'America/Denver',hour:'numeric',minute:'numeric',hourCycle:'h23',weekday:'long',month:'numeric',day:'numeric'}).formatToParts(at),part=t=>parts.find(p=>p.type===t)?.value,hour=Number(part('hour')),minute=Number(part('minute')),month=Number(part('month')),weekend=['Friday','Saturday'].includes(part('weekday')),genres=(d.genres||[]).map(g=>g.name||g),keywords=(d.keywords?.keywords||[]).map(k=>k.name||k),words=[movie.title,movie.overview,d.overview,...genres,...keywords].join(' ').toLowerCase(),ledger=[],nudge=[],match=re=>new RegExp("\\b(?:"+re.source+")","i").test(words),clamp=n=>Math.max(0,Math.min(1,n)),finite=Number.isFinite;
 const row=(title,value,raw,why,group='atmosphere')=>ledger.push({title,value:String(value),raw,points:raw,group,why});
 const numeric=(title,value,unit,raw,why)=>row(title,finite(value)?value+unit:'Unavailable',finite(value)?raw:0,finite(value)?why:'No source value. This factor contributes zero.');
 const c=fit?.connection,bases=c?{Director:c.directors.length*3,Writers:Math.min(2,c.writers.length)*2,Keywords:Math.min(4,c.keywords.length)*1.1,Genres:Math.min(2,c.genres.length)*.25}:{},base=Object.values(bases).reduce((a,b)=>a+b,0);let taste=fit?.score||0;
 row('Taste connection',taste>0?'Established':'No strong connection',0,(fit?.reasons?.join('. ')||'No established personal match.')+' Summary of the taste components below; counted once.','summary');
 const cold=match(/winter|snow|isolat|mountain|remote/),hot=match(/desert|summer|heat|sun/),dread=match(/horror|mystery|thriller|noir/),wet=match(/rain|storm|sea|ocean/),exposed=match(/desert|landscape|survival|mountain/),night=match(/noir|night|dream|surreal/);
 numeric('Temperature',w.temperature_2m,'°F',.16*(cold?clamp((55-w.temperature_2m)/25):hot?clamp((w.temperature_2m-65)/25):0),'Modeled Kalispell air temperature. Cold imagery ramps below 55°F; heat imagery above 65°F. '+(cold?'Cold or isolation metadata matches.':hot?'Heat or summer metadata matches.':'Neither motif matches this film.'));
 numeric('Feels like',w.apparent_temperature,'°F',.08*(cold?clamp((55-w.apparent_temperature)/25):hot?clamp((w.apparent_temperature-65)/25):0),'A smaller comfort pairing using apparent temperature. Its maximum is half the temperature weight because the inputs overlap.');
 numeric('Humidity',w.relative_humidity_2m,'%',.12*(match(/swamp|body horror|fung|decay|humid/)?clamp((w.relative_humidity_2m-55)/40):match(/desert|drought/)?clamp((45-w.relative_humidity_2m)/40):0),'Damp organic motifs ramp above 55%; desert or drought motifs below 45%. Requires matching film metadata.');
 numeric('Cloud cover',w.cloud_cover,'%',.12*(dread?clamp(w.cloud_cover/100):match(/adventure|summer/)?clamp(1-w.cloud_cover/100):0),'Clouds pair with suspense; clear skies pair with adventure or summer. This is an editorial pairing, not a mood measurement.');
 numeric('Rain / snow',w.precipitation,' inches',wet?.12*clamp(w.precipitation/.1):0,'Actual modeled precipitation pairs with rain, storm or water motifs. Ramps to its limit at 0.1 inches; dry weather contributes zero.');
 numeric('Wind',w.wind_speed_10m,' mph',exposed?.10*clamp(w.wind_speed_10m/25):0,'Exposed landscape or survival metadata pairs with wind, ramping to its limit at 25 mph.');
 numeric('Gusts',w.wind_gusts_10m,' mph',exposed&&finite(w.wind_speed_10m)?.06*clamp((w.wind_gusts_10m-w.wind_speed_10m)/20):0,'Only the gust excess over steady wind counts, avoiding a second full wind bonus. Requires exposed landscape metadata and both measurements.');
 numeric('Air pressure',w.pressure_msl,' hPa',dread?.06*clamp((1015-w.pressure_msl)/20):0,'Suspense gets a tiny editorial low-pressure pairing below 1015 hPa. One pressure reading cannot establish a storm or pressure trend.');
 numeric('Surface pressure',w.surface_pressure,' hPa',finite(w.pressure_msl)&&match(/mountain|altitude|climb/)?.04*clamp((w.pressure_msl-w.surface_pressure)/150):0,'The sea-level versus surface pressure gap supplies a tiny terrain pairing for mountain or climbing metadata. Never treated as a second storm signal.');
 const daylight=daily.daylight_duration?.[0];numeric('Daylight',finite(daylight)?Number((daylight/3600).toFixed(1)):undefined,' hours',finite(daylight)?((night||dread)?.06*clamp((14-daylight/3600)/6):match(/summer|adventure/)?.06*clamp((daylight/3600-10)/6):0):0,'Short days pair with night or suspense; long days with summer or adventure. Astronomical daylight, not sunshine hours.');
 const sunset=daily.sunset?.[0],sunMatch=typeof sunset==='string'&&sunset.match(/T(\d{2}):(\d{2})/),sunHour=sunMatch?Number(sunMatch[1])+Number(sunMatch[2])/60:null;
 const localDate=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Denver',year:'numeric',month:'2-digit',day:'2-digit'}).format(at),sunsetMinutes=sunHour!==null&&sunset?.slice(0,10)===localDate?sunHour*60-(hour*60+minute):null,endingGap=sunsetMinutes!==null&&d.runtime>0?Math.abs(d.runtime-sunsetMinutes):null;
 row('Sunset',sunsetMinutes!==null?sunMatch[1]+':'+sunMatch[2]:'Unavailable',sunsetMinutes!==null?(sunsetMinutes>0&&endingGap!==null?.12*clamp(1-endingGap/30):sunsetMinutes<=0&&night?.06:0):0,'A film ending within 30 minutes of today’s sunset earns up to 0.12 at exact alignment. After sunset, night imagery earns 0.06. Minute-accurate local time; missing or other-day sunsets earn zero.');
 numeric('Rain probability',daily.precipitation_probability_max?.[0],'%',wet?.06*clamp(daily.precipitation_probability_max?.[0]/100):0,'Today’s forecast probability supplies anticipation, separately from current precipitation, with half the current-rain weight.');
 const lunar=lunarReading(m,words);row('Moon',m.name+' · '+m.illumination+'% lit',Math.max(lunar.theme?.06:0,match(/werewolf|moon/)?.08*(m.illumination/100):match(/cosmic|space/)?.04*(m.illumination/100):0),'Phase-symbolism motif match earns 0.06. Literal moon/werewolf or cosmic imagery can earn a larger illumination pairing; only the larger bonus is counted. Approximate astronomy; sourced modern witchcraft symbolism, not a claim of lunar effects on your mind.');
 const runtime=Number(d.runtime),runtimePoints=finite(runtime)&&runtime>0?(!weekend&&hour>=21?.12*clamp((150-runtime)/60):weekend?.08*clamp((runtime-100)/60):0):0;
 row('Local clock',part('weekday')+' · '+hour+':00 hour',0,'Controls runtime and after-sunset rules below. No duplicate points for the clock itself.','context');
 const season=month>=9&&month<=11?'Autumn':month>=6&&month<=8?'Summer':month>=3&&month<=5?'Spring':'Winter';
 row('Season',season,.08*(season==='Autumn'&&match(/horror|witch|supernatural|autumn/)?1:season==='Winter'&&cold?1:season==='Summer'&&hot?1:season==='Spring'&&match(/romance|growth|garden/)?1:0),'Calendar season pairs with autumn horror, winter isolation, summer heat or spring romance/growth. It does not diagnose your feelings.');
 row('Runtime',runtime>0?runtime+' minutes':'Not supplied',runtimePoints,weekend?'Friday/Saturday allows a small long-film bonus above 100 minutes.':hour>=21?'After 21:00 on a weekday, shorter films ramp up to 0.12 at 90 minutes.':'No late-weekday or weekend runtime rule applies.');
 const recent=records.filter(r=>r.watchedAt&&finite(Date.parse(r.watchedAt))&&at-Date.parse(r.watchedAt)>=0&&at-Date.parse(r.watchedAt)<=30*86400000&&(r.rating>=4||r.favorite||r.owned||r.rewatches>1)),year=Number((movie.release_date||d.release_date||'').slice(0,4)),era=recent.filter(r=>Number((r.release_date||'').slice(0,4))>0&&Math.abs(Number(r.release_date.slice(0,4))-year)<=10);
 row('Release year',year||'Unknown',year&&era.length?.10*Math.min(1,era.length/3):0,era.length?'Within ten years of '+era.map(r=>r.title).join(', ')+', positively recorded in the last 30 days. Small era continuity, not an assumed viewing streak.':'No positive diary record in the last 30 days supplies an era match.');
 for(const [title,value] of [['Director',(d.credits?.crew||[]).filter(x=>x.job==='Director').map(x=>x.name)],['Writers',[...new Set((d.credits?.crew||[]).filter(x=>['Writer','Screenplay','Story'].includes(x.job)).map(x=>x.name))]],['Genres',genres],['Keywords',keywords]])row(title,value.join(', ')||'Unavailable',bases[title]||0,c&&bases[title]?'Matched '+c[title==='Director'?'directors':title.toLowerCase()].join(', ')+' with '+c.seedTitle+'. Base taste points before affection bonuses.':'No match in the strongest established taste connection. Zero taste points from this component.','taste');
 row('Local screening',local?'Listed in Kalispell':'No matched current listing',local?.15:0,'A current exact-title calendar match earns 0.15 for the opportunity to see it locally. No listing supplies zero.');
 row('Dated diary records',recent.length?recent.map(r=>r.title).join(', '):'No recent positive dated records',0,'Only positive diary dates within 30 days feed the release-year rule. Backfilled dates are not used to assert a streak or viewing order.','context');
 const headlines=(context?.news||[]).filter(n=>finite(Date.parse(n.publishedAt))&&at-Date.parse(n.publishedAt)>=0&&at-Date.parse(n.publishedAt)<=14*86400000),tokens=[movie.title,...(d.credits?.crew||[]).filter(x=>['Director','Writer','Screenplay','Story'].includes(x.job)).map(x=>x.name)].filter(t=>t&&t.length>=5),related=headlines.find(n=>tokens.some(t=>(' '+String(n.title).toLowerCase().replace(/[^a-z0-9]+/g,' ')+' ').includes(' '+t.toLowerCase().replace(/[^a-z0-9]+/g,' ').trim()+' ')));
 row('Recent film news',headlines.length+' fresh dated headlines checked',related?.08:0,related?'Names this film or a credited creator: '+related.title+'. Tiny topicality bonus, not evidence that you care.':'No full-name/title match in a headline from the last 14 days. Zero topicality points.');
 row('Ownership / favorites',records.filter(r=>r.owned||r.favorite).length+' records',base*((c?.owned?.5:0)+(c?.favorite?.5:0)),c&&(c.owned||c.favorite)?c.seedTitle+' is '+[c.owned?'owned':null,c.favorite?'a favorite':null].filter(Boolean).join(' and ')+'. Each adds 50% of its matched base taste points.':'The strongest connected record is neither owned nor favorited. Counts alone supply no points.','taste');
 row('Repeat watches',records.filter(r=>r.rewatches>1).length+' records',c?.rewatches>1?base*.4:0,c?.rewatches>1?'Repeated viewing of '+c.seedTitle+' adds 40% of its matched base taste points.':'No repeat-watch affection in the strongest connection. Counts alone supply no points.','taste');
 row('High ratings',records.filter(r=>r.rating>=4).length+' records',c?.rating>=4?base*(c.rating-3)*.6:0,c?.rating>=4?c.seedTitle+' rated '+c.rating+'/5: adds '+Math.round((c.rating-3)*60)+'% of matched base taste points.':'No high rating in the strongest connection. Counts alone supply no points.','taste');
 if(!c&&taste)row('Unitemized taste',taste,taste,'Legacy taste score supplied without component metadata. Kept once; no invented breakdown.','taste');
 const profile=movie.profileFit;if(profile?.score>0){row('Written taste profile',profile.themes.join(', '),profile.score,'Explicit interests from the supplied STATIC profile. Thematic matching, not a watched-film rating.','taste');taste+=profile.score;}
 const raw=ledger.filter(x=>x.group==='atmosphere').reduce((s,x)=>s+x.raw,0),scale=raw>.8?.8/raw:1;for(const item of ledger)if(item.group==='atmosphere')item.points=item.raw*scale;
 const atmosphere=Math.min(.8,raw);row('Inferred atmosphere',atmosphere.toFixed(3)+' points',0,'Subtotal of the editorial context rules. '+(scale<1?'All context contributions were scaled proportionally to the 0.8-point cap.':'Below the 0.8-point cap.')+' Counted once; your mood remains unknown.','summary');
 explainConditions(movie,ledger,context,at,sunsetMinutes,lunar);for(const title of ['Sunset','Air pressure','Moon']){const item=ledger.find(x=>x.title===title);if(item&&item.value!=='Unavailable'&&(title!=='Moon'||lunar.theme||item.points>0))nudge.push(item.story);}if(!nudge.length){const item=ledger.find(x=>x.group==='atmosphere'&&x.points>0);if(item)nudge.push(item.story);}
 return {...movie,fit:fit||{score:0,reasons:[]},oracle:{score:taste+atmosphere,tasteScore:taste,atmosphereScore:atmosphere,contextScale:scale,nudge,ledger,related,moon:m,checkedAt:context?.checkedAt||null,verdict:(taste>0?'Personal taste supplies '+taste.toFixed(3)+' points.':'No strong personal taste match was established.')+' Context supplies '+atmosphere.toFixed(3)+' of at most 0.800 points. These are editorial ranking rules, not scientific predictions of enjoyment.'}};
 }
 function explainConditions(movie,ledger,context,at,sunsetMinutes,lunar){
  const d=movie.meta||movie,title=movie.title||'this film',w=context?.weather?.current||{},genres=(d.genres||[]).map(g=>g.name||g),keywords=(d.keywords?.keywords||[]).map(k=>k.name||k),words=[title,movie.overview,d.overview,...genres,...keywords].join(' ').toLowerCase(),has=re=>new RegExp('\\b(?:'+re.source+')','i').test(words),motif=(re,fallback)=>keywords.find(k=>new RegExp('\\b(?:'+re.source+')','i').test(k))||genres.find(g=>new RegExp('\\b(?:'+re.source+')','i').test(g))||fallback,minutes=n=>{const v=Math.round(Math.abs(n)),h=Math.floor(v/60),m=v%60;return h?(h+' hour'+(h===1?'':'s')+(m?' '+m+' minute'+(m===1?'':'s'):'')):v+' minute'+(v===1?'':'s');},runtime=Number(d.runtime),finish=Number.isFinite(sunsetMinutes)&&runtime>0?runtime-sunsetMinutes:null;
  const pressureSource={label:'Pressure explained · National Weather Service',url:'https://www.weather.gov/jkl/education'},moonSource={label:'Moon symbolism · Christopher Penczak',url:'https://christopherpenczak.com/2013/07/29/planetary-magic-2-the-moon-manifestation-and-psychic-ability/'};
  for(const item of ledger){let story='',source=null;
   switch(item.title){
    case 'Temperature':story='Kalispell’s modeled temperature is '+item.value+'. '+(has(/winter|snow|isolat|mountain|remote/)?title+' carries '+motif(/winter|snow|isolat|mountain|remote/,'cold or isolation imagery')+'. '+(w.temperature_2m<55?'Let the film take that chill somewhere worse while you remain indoors.':'The film offers the chill the afternoon has declined to provide; that is a contrast, so no cold-weather bonus.') :has(/desert|summer|heat|sun/)?title+' carries '+motif(/desert|summer|heat|sun/,'heat imagery')+'. '+(w.temperature_2m>65?'A warm day can bleed straight into its landscape. The room and the film have agreed on the temperature.':'The day is cooler than that imagery, so the thermal pairing earns nothing.'):'The temperature gives no particular reason to choose '+title+'. The Oracle cannot put a snowdrift into its metadata.');break;
    case 'Feels like':story='The modeled air feels like '+item.value+'. '+(item.points>0?'That felt temperature reinforces the '+motif(/winter|snow|isolat|mountain|remote|desert|summer|heat|sun/,'thermal imagery')+' in '+title+'. Your couch remains the more sensible location.':'It does not strengthen this film’s temperature pairing. A thermometer is not obliged to endorse every movie.');break;
    case 'Humidity':story='Relative humidity is '+item.value+'. '+(has(/desert|drought/)?'The dry '+motif(/desert|drought/,'landscape')+' metadata in '+title+' makes '+(item.points>0?'this dry air a fitting accomplice. Dust outside, dust on screen.':'a tempting contrast, but the actual humidity does not earn a dry-landscape bonus.') :has(/swamp|body horror|fung|decay|humid/)?title+' has '+motif(/swamp|body horror|fung|decay|humid/,'organic unpleasantness')+'. '+(item.points>0?'Damp air helps that atmosphere follow you off the screen. Something seems to be growing in the room.':'The air is too dry for that damp-and-decaying pairing. The rot must supply its own moisture.'):'No damp or drought motif in '+title+' answers this humidity. It stays a condition, not a recommendation.');break;
    case 'Cloud cover':story='Cloud cover is '+item.value+'. '+(item.points>0?(has(/horror|mystery|thriller|noir/)?title+' has '+motif(/horror|mystery|thriller|noir/,'suspense')+'. '+(w.cloud_cover>70?'The sky has put a lid on the evening. A film with something to hide belongs under it.':'There is only a little cloud cover, so the suspicious-sky argument is correspondingly small.') :title+' has '+motif(/adventure|summer/,'open-air imagery')+'. Clearer skies offer it an open door. Someone on screen can make the reckless expedition.'):title+' offers no matching suspense or open-air motif. This sky does not distinguish it from the next film.');break;
    case 'Rain / snow':story='Modeled precipitation is '+item.value+'. '+(item.points>0?'The '+motif(/rain|storm|sea|ocean/,'water imagery')+' in '+title+' has an accomplice outside. The water can cross the border of the screen.':w.precipitation===0?'There is no current modeled rain to lend '+title+' a watery atmosphere. No imaginary storm has been scheduled.':title+' has no matching water motif. The weather may be wet; the argument is not.');break;
    case 'Wind':story='Steady wind is '+item.value+'. '+(item.points>0?'The '+motif(/desert|landscape|survival|mountain/,'exposed landscape')+' in '+title+' lets that movement continue on screen. Let somebody else do the walking.':title+' has no exposed-landscape or survival connection for this wind to catch. It remains outside the recommendation.');break;
    case 'Gusts':story='Gusts reach '+item.value+(Number.isFinite(w.wind_speed_10m)?', '+Math.max(0,w.wind_gusts_10m-w.wind_speed_10m).toFixed(1)+' mph above steady wind.':'.')+' '+(item.points>0?'That extra shove suits the '+motif(/desert|landscape|survival|mountain/,'exposure')+' in '+title+'. The landscape does not hold still.':'That change in force supplies no extra argument for '+title+'. The Oracle has declined to mistake a gust for a plot.');break;
    case 'Air pressure':source=pressureSource;story='Sea-level pressure is '+item.value+'. '+(w.pressure_msl<1005?'That is below the standard sea-level reference of 1013.25 hPa. Low-pressure systems tend to involve rising air, which can produce clouds and precipitation. ':w.pressure_msl>1020?'That is above the standard sea-level reference of 1013.25 hPa. High-pressure systems often involve sinking air and fairer skies. ':'It sits near the standard sea-level reference of 1013.25 hPa. Low-pressure systems can encourage clouds and precipitation, but this reading alone does not establish one here. ')+(item.points>0?'The Oracle borrows that unsettled-weather association for '+title+' and its '+motif(/horror|mystery|thriller|noir/,'suspense')+'. Atmospheric instability outside, uncertainty on screen.':'There is no strong low-pressure argument for '+title+' from this reading. The barometer has not promised a storm.');break;
    case 'Surface pressure':source=pressureSource;story='Pressure at the modeled ground elevation is '+item.value+'. Air pressure decreases with altitude, so this is lower than the sea-level-adjusted reading. '+(item.points>0?'The Oracle uses that terrain association for '+title+' and its '+motif(/mountain|altitude|climb/,'mountain imagery')+'. Thin air as a setting, not a prophecy.':'Nothing in '+title+' calls for a mountain or climbing pairing. Low surface pressure here is not proof of approaching bad weather.');break;
    case 'Daylight':story='Today has '+item.value+' of astronomical daylight. '+(item.points>0?(has(/noir|night|dream|surreal|horror|mystery|thriller/)?'A shorter light window gives '+title+' and its '+motif(/noir|night|dream|surreal|horror|mystery|thriller/,'night imagery')+' more evening to inhabit. The day closes around it.':'The longer light window suits '+title+' and its '+motif(/summer|adventure/,'summer imagery')+'. An afternoon with room to wander.'):title+' supplies no daylight-linked motif here. The length of the day remains impressive without earning a vote.');break;
    case 'Sunset':story=Number.isFinite(sunsetMinutes)?(sunsetMinutes>0?'Sunset is in '+minutes(sunsetMinutes)+'. ':'Sunset was '+minutes(sunsetMinutes)+' ago. ')+(finish!==null?'Start '+title+' now and its '+runtime+'-minute runtime puts the credits '+(Math.abs(finish)<=10?'within ten minutes of sunset':minutes(finish)+' '+(finish<0?'before':'after')+' sunset')+'. '+(sunsetMinutes>0&&Math.abs(finish)<=30?'The film ends as the light changes. An unusually well-timed handover from screen to evening.':sunsetMinutes>0&&finish>30?'It begins in the remaining light and continues into the night. The Oracle cannot honestly call the ending synchronized.':sunsetMinutes>0?'The film would finish with daylight still left. Keep the evening, rather than surrendering all of it.':has(/noir|night|dream|surreal/)?'Its '+motif(/noir|night|dream|surreal/,'night imagery')+' can begin after the sun has already left.':'The sun has already left; this is an evening screening, not a sunset alignment.'):'The runtime is missing, so the Oracle cannot promise when the credits meet the sky.'):'Today’s local sunset was not supplied. No ending time is invented for '+title+'.';break;
    case 'Rain probability':story='Today’s maximum rain probability is '+item.value+'. '+(item.points>0?'The possibility of rain gives '+title+' and its '+motif(/rain|storm|sea|ocean/,'water imagery')+' a little anticipation. A forecast of atmosphere, not a claim that rain is falling.':'No forecast-and-water pairing strengthens '+title+' here. An umbrella and a recommendation remain separate questions.');break;
    case 'Moon':source=moonSource;story='The calculated moon is '+item.value+'. '+lunar.description+' '+(lunar.theme?'The Oracle connects that symbolism to '+title+' through its '+lunar.theme+' metadata. '+lunar.invitation:'No matching symbolic motif was found in '+title+'. The moon is allowed to mean something without pretending it chose this film.');break;
    case 'Local clock':story='It is '+new Intl.DateTimeFormat('en-US',{timeZone:'America/Denver',weekday:'long',hour:'numeric',minute:'2-digit'}).format(at)+' in Kalispell. The Oracle uses this actual minute for '+title+'’s sunset timing and runtime argument. No extra points are awarded just for owning a clock.';break;
    case 'Season':story='It is '+item.value.toLowerCase()+'. '+(item.points>0?title+' carries '+motif(/horror|witch|supernatural|autumn|winter|snow|isolat|mountain|remote|desert|summer|heat|sun|romance|growth|garden/,'seasonal imagery')+'. The calendar and the film have found a shared occupation.':'No seasonal theme in '+title+' earns this pairing. The calendar has a suggestion, but no evidence against the film.');break;
    case 'Runtime':story=runtime>0?title+' takes '+runtime+' minutes. '+(item.points>0?'At this hour and on this day, that length fits the available evening. The clock has signed off on the commitment.':'This is neither a rewarded late-weekday short film nor a rewarded weekend long film. The sunset tile makes the more specific timing argument.'):'No runtime is supplied for '+title+'. The Oracle will not guess how much evening it consumes.';break;
    case 'Director':case 'Writers':case 'Genres':case 'Keywords':story=item.points>0?item.why.replace(/ Base taste points before affection bonuses\./,' That is a reason to follow this connection into '+title+'.'):title+' has '+item.value+'. None connects to the strongest positive record used for this pick. The Oracle can suggest a discovery without forging a family tree.';break;
    case 'Ownership / favorites':story=item.points>0?item.why.split('. Each adds')[0]+'. That affection strengthens the actual connection to '+title+'. A shelf can be a better witness than a passing click.':'No owned or favorited film supplies the strongest connection to '+title+'. The Oracle has no shelf-based argument to make.';break;
    case 'Repeat watches':story=item.points>0?'You returned to the film connected to '+title+'. Choosing it again is a stronger witness than merely encountering it once.':'No recorded repeat viewing strengthens '+title+'’s strongest connection. Missing repeats are not evidence that you disliked anything.';break;
    case 'High ratings':story=item.points>0?item.why.split(': adds')[0]+'. That recorded affection carries into '+title+' through the actual shared metadata above.':'No high rating supports '+title+'’s strongest connection. A watchlist entry would not substitute for one.';break;
    case 'Release year':story=title+' was released in '+item.value+'. '+(item.points>0?item.why+' A small continuation of an era you recently recorded liking.':'No recent positive diary date supplies a nearby-era argument. An old affection has not expired; this particular bonus simply has no date to use.');break;
    case 'Dated diary records':story=item.value==='No recent positive dated records'?'No recent positive diary dates are available for '+title+'’s era comparison. The Oracle cannot turn an undated ratings export into last week’s watching.':'These positive diary dates support '+title+'’s release-year comparison: '+item.value+'. They document dates, not a proven streak.';break;
    case 'Local screening':story=item.points>0?title+' has a matched current Kalispell screening. For once, the Oracle’s grand design involves getting out of the house.':'No current Kalispell screening is matched to '+title+'. It cannot earn a local-theater argument from an absent listing.';break;
    case 'Recent film news':story=item.points>0?item.why+' That puts '+title+' near a current conversation, without proving it is yours.':'The checked fresh headlines do not name '+title+' or a credited creator. The news cycle has offered no reason to move it to tonight.';break;
    default:story=item.why;
   }
   if(item.value==='Unavailable'||item.value==='Not supplied')story='This source value was not supplied. The Oracle has no '+item.title.toLowerCase()+' argument for '+title+'.';
   item.story=story;if(source)item.source=source;
  }
 }
 function lunarReading(m,words){
  const waxing=m.name.startsWith('Waxing')||m.name==='First quarter',waning=m.name.startsWith('Waning')||m.name==='Last quarter',pattern=waxing?/ambition|quest|journey|growth|coming of age|transformation|adventure/:waning?/grief|loss|mourning|memory|haunt|exorcism|revenge|farewell|death|rebirth/:m.name==='New moon'?/protection|rebirth|new beginning|exorcism/:/werewolf|moon|ritual|transformation/;
  const found=words.match(new RegExp('\\b(?:'+pattern.source+')','i')),theme=found?.[0]||null;
  const description=waxing?'In Christopher Penczak’s account of modern witchcraft, waxing light belongs to building and receiving.':waning?'In Christopher Penczak’s account of modern witchcraft, waning light belongs to banishing and releasing.':m.name==='New moon'?'Christopher Penczak associates the dark end of the lunar cycle with protection and banishment.':'Christopher Penczak treats the full moon as the peak of the cycle’s magical power.';
  return {theme,description,invitation:waxing?'Something reaching toward a larger life while the light grows.':waning?'Something that will not leave, under a moon rehearsing its disappearance.':m.name==='New moon'?'The lights have gone out. Consider what gets to begin again.':'The Oracle borrows the symbolism of a cycle at its limit. It expects the film to make a scene.'};
 }
 function reading(movie,fit,at=Date.now()){
  const d=movie.meta||movie,keywords=(d.keywords?.keywords||[]).map(k=>k.name||k),genres=(d.genres||[]).map(g=>g.name||g),words=[movie.title||'',...keywords,...genres,movie.overview||''].join(' ').toLowerCase();
  const cases=[
   [/motel|psycho/, 'There are vacancies. There are also concerns.', ['A perfectly ordinary place to spend the night, provided you ignore absolutely everything about it. The Oracle suggests enjoying the questionable hospitality from somewhere with your own locks.', 'For the pleasure of watching a familiar place gradually fail its basic job of being a place. Stay on the couch. You have already checked in.']],
   [/archive|archival|chronovisor/, 'Someone has opened the wrong folder.', ['The kind of rabbit hole that begins with a document and ends with you wondering whether the document has been reading you back. A little patience. A little obsession. Absolutely no productive use of the afternoon.', 'A film for the part of you that thinks one more tape, one more footnote, one more obscure connection might finally explain it. The Oracle has brought a shovel.']],
   [/batman|gotham/, 'The city has outsourced its problems to a costume.', ['Gotham could try street lighting and social services. Instead, it has an emotionally damaged man in expensive ears. The Oracle would like to see where this policy leads.', 'A city where every public problem eventually becomes a fistfight between men who have spent too much on clothes. There is probably a better system. Tonight, we are watching this one.']],
   [/vampire/, 'An immortal person is being a nuisance.', ['Centuries to develop a personality, and still mostly interested in necks. The Oracle respects the commitment, if very little else.', 'A film about people who have had hundreds of years to get their lives together. Somehow, the curtains are still closed.']],
   [/werewolf/, 'The moon has become somebody’s problem.', ['For the ancient terror of becoming considerably less employable once a month. The Oracle suggests staying indoors, which is also the point of the exercise.', 'A little bodily betrayal under inadequate outdoor lighting. The moon claims it has no responsibility. Nobody believes it.']],
   [/zombie|living dead/, 'The dead have developed a scheduling conflict.', ['Death was supposed to settle things. Apparently there is more walking to do. The Oracle admires a horror film with such an unreasonable workload.', 'The dead are back, which makes several ordinary errands much harder. A film for appreciating how thoroughly the normal day can fall apart.']],
   [/time travel|time loop/, 'The afternoon has refused to end.', ['Something for the terrible possibility that a bad day could also become a format. The Oracle recommends watching it once before making any longer commitment.', 'Time, usually dependable enough to be boring, has started doing tricks. Try to remember which version of everyone you are currently annoyed with.']],
   [/heist|robbery/, 'The plan has too many moving parts.', ['Somebody has assembled a very complicated alternative to having a job. The Oracle is here for the part where the diagram stops helping.', 'For the pleasure of watching a beautiful plan acquire fingerprints, panic, and one guy nobody should have invited.']],
   [/undercover|police|espionage|spy|crime/, 'Trust absolutely nobody.', ['Tonight calls for a film that makes a man introducing himself feel like a threat. By the end, you should distrust the haircut, the handshake, and the second phone.', 'An evening of lies, divided loyalties, and people who should have chosen a less complicated occupation. The Oracle has checked everyone’s references. They are also lies.']],
   [/body horror|mutat|fung|parasite|decay/, 'The body has other plans.', ['Something unpleasant for the part of your brain that keeps asking whether skin is really necessary. The Oracle suggests eating first.', 'A little organic unpleasantness. Flesh making decisions without consulting its owner. Put the snacks somewhere you cannot see them.']],
   [/found footage|mockumentary|surveillance|videotape/, 'Someone should have stopped recording.', ['For the pleasure of watching a recording become a very bad idea. Every recovered tape is, at some level, a customer complaint from beyond the grave.', 'An artifact from the department of things that should have stayed in a box. The Oracle has pressed play. Naturally, nobody has checked the box.']],
   [/cosmic|space|alien|extraterrestrial/, 'The universe is being rude again.', ['Something with enough scale to make the room feel briefly inadequate. A whole indifferent universe, delivered to the couch.', 'Tonight’s modest proposal: consider how enormous everything is, then become concerned about a noise in the kitchen.']],
   [/surreal|dream|hallucinat|experimental/, 'The exits have been rearranged.', ['A film for the pleasure of losing your bearings on purpose. Leave one lamp on. It will not explain anything, but it can stand there looking useful.', 'Tonight, ordinary reality can wait in the car. The Oracle has brought you something with a less cooperative floor plan.']],
   [/isolation|isolated|remote|snow|winter|mountain/, 'The nearest neighbor is too far away.', ['Let the landscape do some of the threatening. A room, a long distance, and the growing suspicion that the long distance was the point.', 'Something spacious enough for silence to start behaving badly. The Oracle would prefer that you stayed comfortably indoors for this experiment.']],
   [/grief|bereave|memory|memories|loss|mourning/, 'A small object. An enormous feeling.', ['For when a film gets its hands on some ordinary little thing and makes it impossible to look at normally again. Emotional damage, administered through household objects.', 'Something that may leave a perfectly normal room feeling recently abandoned. The Oracle recommends allowing the credits to finish.']],
   [/witch|folk horror|ritual|cult/, 'Do not join the local committee.', ['A little ritual, a little community, a terrible reason to accept an invitation. The Oracle has declined the potluck on your behalf.', 'For the ancient human terror of arriving somewhere picturesque and discovering that everyone already knows your name.']],
   [/romance|romantic|love affair/, 'Two people. Several avoidable problems.', ['The Oracle has selected a film about the catastrophic administrative consequences of wanting somebody. Very little can be solved by being sensible.', 'Some tenderness, with the usual risk of someone saying the wrong thing at the only moment it mattered.']],
   [/comedy/, 'There is no dignified way through this.', ['A film for watching somebody’s bad idea become everybody’s afternoon. The Oracle respects a disaster that commits to the bit.', 'Tonight’s offering concerns the human animal and its apparently unlimited capacity to make things worse. At least it has the decency to be funny.']],
   [/horror|thriller|mystery/, 'The room is probably fine.', ['A controlled deterioration of the evening. The Oracle recommends a familiar room, a working lamp, and absolutely no investigation of that noise.', 'For the pleasure of feeling something is wrong before anyone can explain what. You can remain on the couch. The people in the film have made other arrangements.']],
   [/drama/, 'Let somebody else’s life get complicated.', ['A film that gives ordinary human decisions room to become enormous. The Oracle would like you to leave a little space after the credits.', 'People wanting things, saying the wrong things, then having to live in the same room. Let the credits finish.']]
  ];
  const chosen=cases.find(([pattern])=>pattern.test(words)),variant=(Number(movie.id)||0)%2;
  const heading=chosen?chosen[1]:'A door you have not opened.';
  let text=chosen?chosen[2][variant]:'The Oracle has pulled '+movie.title+' out of the stack. Consider this permission to spend a little time somewhere unfamiliar. It has made no arrangements for your safe return.';
  const c=fit?.connection;
  if(c&&fit.score>0){
   const affection=c.owned?'You have '+c.seedTitle+' on your shelf.':c.rewatches>1?'You went back to '+c.seedTitle+'.':c.favorite?c.seedTitle+' is one of your saved favorites.':c.rating>=4?'You gave '+c.seedTitle+' '+c.rating+'/5.':'';
   if(c.directors.length)text+=' '+affection+' This comes from '+c.directors.join(' and ')+'. The Oracle is following the person who made the previous mess.';
   else if(c.writers.length)text+=' '+affection+' '+c.writers.join(' and ')+' wrote both. Return to the source of the trouble.';
   else if(c.keywords.length)text+=' '+affection+' Both films share '+c.keywords.slice(0,2).join(' and ')+'.';
   else text+=' '+affection+' That is a loose genre connection, so the Oracle is leaving room to be wrong.';
  }
  return {heading,text};
 }
 function compare(pool){
  const ranked=[...pool].sort((a,b)=>b.oracle.score-a.oracle.score),winner=ranked[0];if(!winner)return null;
  const weather=new Set(['Temperature','Feels like','Humidity','Cloud cover','Rain / snow','Wind','Gusts','Air pressure','Surface pressure','Daylight','Sunset','Rain probability']);
  const totals=m=>new Map((m.oracle.ledger||[]).filter(x=>!['summary','context'].includes(x.group)).map(x=>[x.title,x.points]));
  const win=totals(winner),alternatives=ranked.slice(1,4).map(movie=>{
   const other=totals(movie),deltas=[...new Set([...win.keys(),...other.keys()])].map(title=>({title,points:(win.get(title)||0)-(other.get(title)||0)})).filter(x=>Math.abs(x.points)>1e-9),gap=Math.max(0,winner.oracle.score-movie.oracle.score),weatherDelta=deltas.filter(x=>weather.has(x.title)).reduce((s,x)=>s+x.points,0),tie=gap<1e-9;
   return {id:movie.id,title:movie.title,score:movie.oracle.score,taste:movie.oracle.tasteScore,context:movie.oracle.atmosphereScore,gap,tie,close:!tie&&gap<=.1+1e-9,weatherTipped:!tie&&weatherDelta>0&&gap-weatherDelta<=1e-9,gains:deltas.filter(x=>x.points>0).sort((a,b)=>b.points-a.points).slice(0,3),losses:deltas.filter(x=>x.points<0).sort((a,b)=>a.points-b.points).slice(0,3),deltas,connection:movie.fit?.reasons?.join('. ')||'No established personal taste connection.'};
  });
  return {count:ranked.length,winner:{title:winner.title,score:winner.oracle.score,taste:winner.oracle.tasteScore,context:winner.oracle.atmosphereScore},alternatives};
 }
 return {moon,rank,reading,compare};
});
